### ISSUE TITLE
NullPointerException for file user_agents

### ISSUE THREAD

**Issue by cmenke2** [intel-hadoop/HiBench#120]
Hello,

I tried to run the HiBench on only one node with Hadoop 2.7.1, Spark 1.3.1 and Java 1.7.
For the test "aggregation" and "join" I got the following error:

```
Prepare aggregation ...
Exec script: /home/hduser/HiBench-master/workloads/aggregation/prepare/prepare.sh
Parsing conf: /home/hduser/HiBench-master/conf/00-default-properties.conf
Parsing conf: /home/hduser/HiBench-master/conf/10-data-scale-profile.conf
Parsing conf: /home/hduser/HiBench-master/conf/99-user_defined_properties.conf
Parsing conf: /home/hduser/HiBench-master/workloads/aggregation/conf/00-aggregation-default.conf
Parsing conf: /home/hduser/HiBench-master/workloads/aggregation/conf/10-aggregation-userdefine.conf
start HadoopPrepareAggregation bench
hdfs rm -r: /usr/local/hadoop//bin/hadoop --config /usr/local/hadoop/etc/hadoop fs -rm -r -skipTrash hdfs://localhost:54310/HiBench/Aggregation/Input
15/08/03 10:04:25 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Deleted hdfs://localhost:54310/HiBench/Aggregation/Input
Pages:120, USERVISITS:1000
Submit MapReduce Job: /usr/local/hadoop//bin/hadoop --config /usr/local/hadoop/etc/hadoop jar /home/hduser/HiBench-master/src/autogen/target/autogen-4.0-SNAPSHOT-jar-with-dependencies.jar HiBench.DataGen -t hive -b hdfs://localhost:54310/HiBench/Aggregation -n Input -m 12 -r 6 -p 120 -v 1000 -o sequence
15/08/03 10:04:33 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
15/08/03 10:04:37 WARN mapreduce.JobResourceUploader: Hadoop command-line option parsing not performed. Implement the Tool interface and execute your application with ToolRunner to remedy this.
15/08/03 10:04:39 INFO HiBench.HtmlCore: WARNING: dict empty!!!
15/08/03 10:04:39 INFO HiBench.HtmlCore: WARNING: dict empty!!!
15/08/03 10:04:39 INFO HiBench.HtmlCore: WARNING: dict empty!!!
15/08/03 10:04:40 INFO HiBench.HtmlCore: WARNING: dict empty!!!
15/08/03 10:04:40 INFO HiBench.HtmlCore: WARNING: dict empty!!!
15/08/03 10:04:40 INFO HiBench.HtmlCore: WARNING: dict empty!!!
15/08/03 10:04:40 INFO HiBench.HtmlCore: WARNING: dict empty!!!
15/08/03 10:04:40 INFO HiBench.HtmlCore: WARNING: dict empty!!!
15/08/03 10:04:40 INFO HiBench.HtmlCore: WARNING: dict empty!!!
15/08/03 10:04:40 INFO HiBench.HtmlCore: WARNING: dict empty!!!
15/08/03 10:04:40 INFO HiBench.HtmlCore: WARNING: dict empty!!!
15/08/03 10:04:41 INFO HiBench.HtmlCore: WARNING: dict empty!!!
15/08/03 10:04:41 INFO reduce.EventFetcher: EventFetcher is interrupted.. Returning
15/08/03 10:04:41 INFO HiBench.HiveData$GenerateRankingsReducer: pid: 0, 0 erros, 0 missed
15/08/03 10:04:41 INFO reduce.EventFetcher: EventFetcher is interrupted.. Returning
15/08/03 10:04:41 INFO HiBench.HiveData$GenerateRankingsReducer: pid: 1, 0 erros, 0 missed
15/08/03 10:04:41 INFO reduce.EventFetcher: EventFetcher is interrupted.. Returning
15/08/03 10:04:41 INFO HiBench.HiveData$GenerateRankingsReducer: pid: 2, 0 erros, 0 missed
15/08/03 10:04:41 INFO reduce.EventFetcher: EventFetcher is interrupted.. Returning
15/08/03 10:04:41 INFO HiBench.HiveData$GenerateRankingsReducer: pid: 3, 0 erros, 0 missed
15/08/03 10:04:42 INFO reduce.EventFetcher: EventFetcher is interrupted.. Returning
15/08/03 10:04:42 INFO HiBench.HiveData$GenerateRankingsReducer: pid: 4, 0 erros, 0 missed
15/08/03 10:04:42 INFO reduce.EventFetcher: EventFetcher is interrupted.. Returning
15/08/03 10:04:42 INFO HiBench.HiveData$GenerateRankingsReducer: pid: 5, 0 erros, 0 missed
15/08/03 10:04:43 WARN mapreduce.JobResourceUploader: Hadoop command-line option parsing not performed. Implement the Tool interface and execute your application with ToolRunner to remedy this.
java.io.FileNotFoundException: file:/app/hadoop/tmp/mapred/local/1438589083883/user_agents (No such file or directory)
java.io.FileNotFoundException: file:/app/hadoop/tmp/mapred/local/1438589083883/user_agents (No such file or directory)
java.io.FileNotFoundException: file:/app/hadoop/tmp/mapred/local/1438589083883/user_agents (No such file or directory)
java.io.FileNotFoundException: file:/app/hadoop/tmp/mapred/local/1438589083883/user_agents (No such file or directory)
15/08/03 10:04:47 WARN mapred.LocalJobRunner: job_local1327903863_0002
java.lang.Exception: java.lang.NullPointerException
Caused by: java.lang.NullPointerException
Exception in thread "main" java.io.IOException: Job failed!
        at org.apache.hadoop.util.RunJar.main(RunJar.java:136)
ERROR: Hadoop job /home/hduser/HiBench-master/src/autogen/target/autogen-4.0-SNAPSHOT-jar-with-dependencies.jar HiBench.DataGen failed to run successfully.
Hint: You can goto /home/hduser/HiBench-master/report/aggregation/prepare/conf/../bench.log to check for detailed log.
Opening log tail for you:

        at HiBench.DataGen.run(DataGen.java:19)
        at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
        at HiBench.DataGen.main(DataGen.java:45)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.hadoop.util.RunJar.run(RunJar.java:221)
        at org.apache.hadoop.util.RunJar.main(RunJar.java:136)

ERROR: aggregation prepare failed!
```

My bench.log looks like:

```
15/08/03 10:04:44 INFO mapred.LocalDistributedCacheManager: Localized hdfs://localhost:54310/HiBench/Aggregation/temp/user_agents as file:/app/hadoop/tmp/mapred/local/1438589083883/user_agents
15/08/03 10:04:44 INFO mapred.LocalDistributedCacheManager: Localized hdfs://localhost:54310/HiBench/Aggregation/temp/country_codes as file:/app/hadoop/tmp/mapred/local/1438589083884/country_codes
15/08/03 10:04:44 INFO mapred.LocalDistributedCacheManager: Localized hdfs://localhost:54310/HiBench/Aggregation/temp/search_keys as file:/app/hadoop/tmp/mapred/local/1438589083885/search_keys
...
java.io.FileNotFoundException: file:/app/hadoop/tmp/mapred/local/1438589083883/user_agents (No such file or directory)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(FileInputStream.java:146)
        at java.io.FileInputStream.<init>(FileInputStream.java:101)
        at java.io.FileReader.<init>(FileReader.java:58)
        at HiBench.Visit.<init>(Visit.java:46)
        at HiBench.HiveData$DummyToAccessNoMapper.configure(HiveData.java:389)
        at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:109)
        at org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:78)
        at org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:136)
        at org.apache.hadoop.mapred.lib.DelegatingMapper.map(DelegatingMapper.java:53)
        at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:54)
        at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:453)
        at org.apache.hadoop.mapred.MapTask.run(MapTask.java:343)
        at org.apache.hadoop.mapred.LocalJobRunner$Job$MapTaskRunnable.run(LocalJobRunner.java:243)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
```

While running the test, the file will be generated and the symlink will be set correctly.

Thanks for your help.

**Comment by lvsoft** [comment]
Do not use LocalJob (which is default configuration for an empty mapred-site.xml):
add a property like this:

     <property>
       <name>mapreduce.framework.name</name>
       <value>yarn</value>
     </property>

**Comment by manuzhang** [comment]
Could you add documentation for this ?

**Comment by Ada-Wu** [comment]
I have met the same problem can you share how you fix these?
When I run the run.sh the files are not created and errors also pop up.

**Comment by mwws** [comment]
@Ada-Wu you have to properly config yarn in your Hadoop configuration.

**Comment by Ada-Wu** [comment]
@mwws  Thanks for your suggestion, however I'm running Hibench in Spark stand-alone mode. So can the SQL test be run in stand-alone mode properly?

**Comment by mwws** [comment]
@Ada-Wu Actually above exception happened on data preparing phase and it will launch some mapreduce tasks based on YARN. That's why we need YARN here. 

The Spark part haven't been touched yet when you see this exception, and it's fine to test on Standalone mode for Spark phase.

**Comment by Ada-Wu** [comment]
@mwws  yes I meant this error in prepare.sh! However I tried to ignore such error and executed the run.sh, some other king of FileNotFound exceptions occur too. I've search the Internet for solution, someone said I should add a mapred-site.xml to Hibench(But I found they also use the Yarn mode). Will that work?

**Comment by mwws** [comment]
@Ada-Wu I don't think it could be ignored. prepare.sh will generate a seed file which will be used on next step. That's why you see the FileNotFound exception.

**Comment by Ada-Wu** [comment]
@mwws  So perhaps I need to make a little change at at prepare.sh and instead of using hadoop to generate data try to use Spark?

**Comment by mwws** [comment]
I would vote for the change. Is there any specific reason why we still use mapreduce to generate test data here? @carsonwang

**Comment by Aman-Jain-14** [comment]
I am running in the same error, trying to run this with Hadoop WITHOUT Yarn. Is there a solution to this?

**Comment by Pl4tiNuM** [comment]
Hello, any fix for this issue? I am also trying to run SQL benchmarks over Kubernetes and getting the error above.

The rest of the benchmarks (micro,ml,graph,websearch) work fine.
