### ISSUE TITLE
java.lang.ClassNotFoundException: org.apache.hadoop.hive.conf.HiveConf

### ISSUE THREAD

**Issue by kman99** [intel-hadoop/HiBench#125]
Environment: CDH 3.5 
HiBench: 4.0

When running any spark bench it fails when trying to perform the Hive aggression step.

15/08/21 13:52:24 INFO cluster.SparkDeploySchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/hadoop/hive/conf/HiveConf
        at org.apache.spark.sql.hive.api.java.JavaHiveContext.<init>(JavaHiveContext.scala:30)
        at com.intel.sparkbench.sql.JavaSparkSQLBench.main(JavaSparkSQLBench.java:50)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.apache.spark.deploy.SparkSubmit$.launch(SparkSubmit.scala:358)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:75)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.hive.conf.HiveConf
        at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 9 more

Tried various solutions below to no avail.

http://stackoverflow.com/questions/13333519/error-starting-hive-java-lang-noclassdeffounderror-org-apache-hadoop-hive-conf 
http://community.cloudera.com/t5/Advanced-Analytics-Apache-Spark/I-am-using-a-hive-cotext-in-pyspark-cdh5-3-virtual-box-and-i-get/m-p/24418#U24418

Can anybody explain if the HiveConf classes is being read locally or within HDFS?

**Comment by GayathriMurali** [comment]
No version of CDh has built in Spark SQL. That is the reason you see this error. Download Spark SQL separately from Apache-spark official release. Updated this on the readme as well.
