### ISSUE TITLE
Runall.sh throwing an error

### ISSUE THREAD

**Issue by subhojitpaul** [intel-hadoop/HiBench#135]
Hi..after running the build.sh script and setting up the env variables I am trying to run the runall.sh script and its giving me the following error

Exception in thread "main" java.lang.IllegalArgumentException: java.net.URISyntaxException: Relative path in absolute URI: hdfs://10.188.73.39:9000Input
Caused by: java.net.URISyntaxException: Relative path in absolute URI: hdfs://10.188.73.39:9000Input
        ... 11 more
ERROR: Hadoop job /home/ec2-user/HiBench-master/src/autogen/target/autogen-4.0-SNAPSHOT-jar-with-dependencies.jar HiBench.DataGen failed to run successfully.
Hint: You can goto /home/ec2-user/HiBench-master/report/aggregation/prepare/conf/../bench.log to check for detailed log.
Opening log tail for you:

        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.apache.hadoop.util.RunJar.main(RunJar.java:212)
Caused by: java.net.URISyntaxException: Relative path in absolute URI: hdfs://10.188.73.39:9000Input
        at java.net.URI.checkPath(URI.java:1823)
        at java.net.URI.<init>(URI.java:745)
        at org.apache.hadoop.fs.Path.initialize(Path.java:203)
        ... 11 more
ERROR: aggregation prepare failed!

**Comment by GayathriMurali** [comment]
HDFS master is the value from core-site.xml file. 

![image](https://cloud.githubusercontent.com/assets/7002441/10376888/32609168-6db5-11e5-91ab-2586dd993b3c.png)
