### ISSUE TITLE
*Benchmarks* prepare failed!

### ISSUE THREAD

**Issue by mikehomee** [intel-hadoop/HiBench#136]
Hi! 
I'm currently benchmarking our HDP 2.2 environment (staging)  and saw this HiBench (Thanks!)
Am trying to run the script but it's giving me "prepare failed!"
I did try to run the build-all.sh first (without error) before running run-all.sh
Just trying to run these benchmarks
aggregation
join
terasort
nutchindexing.

I'm using HiBench Ver4.0. 
ANY HELP IS HIGHLY APPRECIATED. THANK YOU!

Prepare aggregation ...
Exec script: /home/hive/HiBench/workloads/aggregation/prepare/prepare.sh
Parsing conf: /home/hive/HiBench/conf/00-default-properties.conf
Parsing conf: /home/hive/HiBench/conf/10-data-scale-profile.conf
Parsing conf: /home/hive/HiBench/conf/99-user_defined_properties.conf
Parsing conf: /home/hive/HiBench/workloads/aggregation/conf/00-aggregation-default.conf
Parsing conf: /home/hive/HiBench/workloads/aggregation/conf/10-aggregation-userdefine.conf
ERROR, execute cmd: '( /usr/hdp/2.2.0.0-2041/hadoop/bin/yarn node -list 2> /dev/null | grep RUNNING )' timedout.
  STDOUT:

  STDERR:

  Please check!
Traceback (most recent call last):
  File "/home/hive/HiBench/bin/functions/load-config.py", line 448, in <module>
    load_config(conf_root, workload_root, workload_folder)
  File "/home/hive/HiBench/bin/functions/load-config.py", line 154, in load_config
    generate_optional_value()
  File "/home/hive/HiBench/bin/functions/load-config.py", line 366, in generate_optional_value
    assert 0, "Get workers from yarn web UI page failed, reason:%s\nplease set `hibench.masters.hostnames` and `hibench.slaves.hostnames` manually" % e
AssertionError: Get workers from yarn web UI page failed, reason:( /usr/hdp/2.2.0.0-2041/hadoop/bin/yarn node -list 2> /dev/null | grep RUNNING ) executed timedout for 5 seconds
please set `hibench.masters.hostnames` and `hibench.slaves.hostnames` manually
/home/hive/HiBench/bin/functions/workload-functions.sh: line 33: .: filename argument required
.: usage: . filename [arguments]
start HadoopPrepareAggregation bench
/home/hive/HiBench/workloads/aggregation/prepare/prepare.sh: line 25: INPUT_HDFS: unbound variable
ERROR: aggregation prepare failed!
Prepare join ...
Exec script: /home/hive/HiBench/workloads/join/prepare/prepare.sh
Parsing conf: /home/hive/HiBench/conf/00-default-properties.conf
Parsing conf: /home/hive/HiBench/conf/10-data-scale-profile.conf
Parsing conf: /home/hive/HiBench/conf/99-user_defined_properties.conf
Parsing conf: /home/hive/HiBench/workloads/join/conf/00-join-default.conf
Parsing conf: /home/hive/HiBench/workloads/join/conf/10-join-userdefine.conf
ERROR, execute cmd: '( /usr/hdp/2.2.0.0-2041/hadoop/bin/yarn node -list 2> /dev/null | grep RUNNING )' timedout.
  STDOUT:

  STDERR:

  Please check!
Traceback (most recent call last):
  File "/home/hive/HiBench/bin/functions/load-config.py", line 448, in <module>
    load_config(conf_root, workload_root, workload_folder)
  File "/home/hive/HiBench/bin/functions/load-config.py", line 154, in load_config
    generate_optional_value()
  File "/home/hive/HiBench/bin/functions/load-config.py", line 366, in generate_optional_value
    assert 0, "Get workers from yarn web UI page failed, reason:%s\nplease set `hibench.masters.hostnames` and `hibench.slaves.hostnames` manually" % e
AssertionError: Get workers from yarn web UI page failed, reason:( /usr/hdp/2.2.0.0-2041/hadoop/bin/yarn node -list 2> /dev/null | grep RUNNING ) executed timedout for 5 seconds
please set `hibench.masters.hostnames` and `hibench.slaves.hostnames` manually
/home/hive/HiBench/bin/functions/workload-functions.sh: line 33: .: filename argument required
.: usage: . filename [arguments]
start HadoopPrepareJoin bench
/home/hive/HiBench/workloads/join/prepare/prepare.sh: line 25: INPUT_HDFS: unbound variable
ERROR: join prepare failed!
Prepare terasort ...
Exec script: /home/hive/HiBench/workloads/terasort/prepare/prepare.sh
Parsing conf: /home/hive/HiBench/conf/00-default-properties.conf
Parsing conf: /home/hive/HiBench/conf/10-data-scale-profile.conf
Parsing conf: /home/hive/HiBench/conf/99-user_defined_properties.conf
Parsing conf: /home/hive/HiBench/workloads/terasort/conf/00-terasort-default.conf
Parsing conf: /home/hive/HiBench/workloads/terasort/conf/10-terasort-userdefine.conf
ERROR, execute cmd: '( /usr/hdp/2.2.0.0-2041/hadoop/bin/yarn node -list 2> /dev/null | grep RUNNING )' timedout.
  STDOUT:

  STDERR:

  Please check!
Traceback (most recent call last):
  File "/home/hive/HiBench/bin/functions/load-config.py", line 448, in <module>
    load_config(conf_root, workload_root, workload_folder)
  File "/home/hive/HiBench/bin/functions/load-config.py", line 154, in load_config
    generate_optional_value()
  File "/home/hive/HiBench/bin/functions/load-config.py", line 366, in generate_optional_value
    assert 0, "Get workers from yarn web UI page failed, reason:%s\nplease set `hibench.masters.hostnames` and `hibench.slaves.hostnames` manually" % e
AssertionError: Get workers from yarn web UI page failed, reason:( /usr/hdp/2.2.0.0-2041/hadoop/bin/yarn node -list 2> /dev/null | grep RUNNING ) executed timedout for 5 seconds
please set `hibench.masters.hostnames` and `hibench.slaves.hostnames` manually
/home/hive/HiBench/bin/functions/workload-functions.sh: line 33: .: filename argument required
.: usage: . filename [arguments]
start HadoopPrepareTerasort bench
/home/hive/HiBench/workloads/terasort/prepare/prepare.sh: line 25: INPUT_HDFS: unbound variable
ERROR: terasort prepare failed!
Prepare nutchindexing ...
Exec script: /home/hive/HiBench/workloads/nutchindexing/prepare/prepare.sh
Parsing conf: /home/hive/HiBench/conf/00-default-properties.conf
Parsing conf: /home/hive/HiBench/conf/10-data-scale-profile.conf
Parsing conf: /home/hive/HiBench/conf/99-user_defined_properties.conf
Parsing conf: /home/hive/HiBench/workloads/nutchindexing/conf/00-nutchindexing-default.conf
Parsing conf: /home/hive/HiBench/workloads/nutchindexing/conf/10-nutchindexing-userdefine.conf
ERROR, execute cmd: '( /usr/hdp/2.2.0.0-2041/hadoop/bin/yarn node -list 2> /dev/null | grep RUNNING )' timedout.
  STDOUT:

  STDERR:

  Please check!
Traceback (most recent call last):
  File "/home/hive/HiBench/bin/functions/load-config.py", line 448, in <module>
    load_config(conf_root, workload_root, workload_folder)
  File "/home/hive/HiBench/bin/functions/load-config.py", line 154, in load_config
    generate_optional_value()
  File "/home/hive/HiBench/bin/functions/load-config.py", line 366, in generate_optional_value
    assert 0, "Get workers from yarn web UI page failed, reason:%s\nplease set `hibench.masters.hostnames` and `hibench.slaves.hostnames` manually" % e
AssertionError: Get workers from yarn web UI page failed, reason:( /usr/hdp/2.2.0.0-2041/hadoop/bin/yarn node -list 2> /dev/null | grep RUNNING ) executed timedout for 5 seconds
please set `hibench.masters.hostnames` and `hibench.slaves.hostnames` manually
/home/hive/HiBench/bin/functions/workload-functions.sh: line 33: .: filename argument required
.: usage: . filename [arguments]
start HadoopPrepareNutchindexing bench
/home/hive/HiBench/workloads/nutchindexing/prepare/prepare.sh: line 25: INPUT_HDFS: unbound variable
ERROR: nutchindexing prepare failed!
Run all done!

**Comment by GayathriMurali** [comment]
Please make sure to start Yarn and hdfs service before running the benchmarks. Also make sure Hadoop and Spark path are correct, HDFS master and Spark master are specified correctly  on the 99-*.conf file.

**Comment by mikehomee** [comment]
Thank you for the reply, @GayathriMurali !

Yarn and HDFS are both running.

I check my settings, and there are the paths.
# Hadoop home
hibench.hadoop.home		/usr/hdp/2.2.0.0-2041/hadoop
# Spark home
hibench.spark.home		/usr/local/spark-1.3.1-bin-hadoop2.6

===============================================
$ ll /usr/local/spark-1.3.1-bin-hadoop2.6/
total 412
drwxr-xr-x 10 root hadoop   4096 Sep  3 11:47 ./
drwxr-xr-x 15 root root     4096 Oct  7 15:40 ../
drwxr-xr-x  2 root hadoop   4096 Apr 11 13:32 bin/
-rw-r--r--  1 root hadoop 278851 Apr 11 13:32 CHANGES.txt
drwxr-xr-x  2 root hadoop   4096 Sep  3 14:05 conf/
drwxr-xr-x  3 root hadoop   4096 Apr 11 13:32 data/
-rw-r--r--  1 root hadoop  12292 Sep  3 12:46 .DS_Store
drwxr-xr-x  3 root hadoop   4096 Apr 11 13:32 ec2/
drwxr-xr-x  3 root hadoop   4096 Apr 11 13:32 examples/
drwxr-xr-x  2 root hadoop   4096 Sep  3 11:47 lib/
-rw-r--r--  1 root hadoop  46083 Apr 11 13:32 LICENSE
-rw-r--r--  1 root hadoop  22559 Apr 11 13:32 NOTICE
drwxr-xr-x  7 root hadoop   4096 Apr 11 13:32 python/
-rw-r--r--  1 root hadoop   3629 Apr 11 13:32 README.md
-rw-r--r--  1 root hadoop    157 Apr 11 13:32 RELEASE
drwxr-xr-x  2 root hadoop   4096 Apr 11 13:32 sbin/


ll /usr/hdp/2.2.0.0-2041/hadoop/
total 192356
drwxr-xr-x 10 root root      4096 Jul  7 20:59 ./
drwxr-xr-x 23 root root      4096 Aug  3 13:12 ../
drwxr-xr-x  2 root root      4096 Jul  7 19:27 bin/
drwxr-xr-x  2 root root     12288 Jul  7 20:59 client/
lrwxrwxrwx  1 root root        16 Nov 20  2014 conf -> /etc/hadoop/conf/
drwxr-xr-x  2 root root      4096 Jul  7 19:27 etc/
-rw-r--r--  1 root root     17053 Nov 20  2014 hadoop-annotations-2.6.0.2.2.0.0-2041.jar
lrwxrwxrwx  1 root root        41 Nov 20  2014 hadoop-annotations.jar -> hadoop-annotations-2.6.0.2.2.0.0-2041.jar
-rw-r--r--  1 root root     67182 Nov 20  2014 hadoop-auth-2.6.0.2.2.0.0-2041.jar
lrwxrwxrwx  1 root root        34 Nov 20  2014 hadoop-auth.jar -> hadoop-auth-2.6.0.2.2.0.0-2041.jar
-rw-r--r--  1 root root   3435192 Nov 20  2014 hadoop-common-2.6.0.2.2.0.0-2041.jar
-rw-r--r--  1 root root   1884091 Nov 20  2014 hadoop-common-2.6.0.2.2.0.0-2041-tests.jar
lrwxrwxrwx  1 root root        36 Nov 20  2014 hadoop-common.jar -> hadoop-common-2.6.0.2.2.0.0-2041.jar
lrwxrwxrwx  1 root root        42 Nov 20  2014 hadoop-common-tests.jar -> hadoop-common-2.6.0.2.2.0.0-2041-tests.jar
-rw-r--r--  1 root root    155929 Nov 20  2014 hadoop-nfs-2.6.0.2.2.0.0-2041.jar
lrwxrwxrwx  1 root root        33 Nov 20  2014 hadoop-nfs.jar -> hadoop-nfs-2.6.0.2.2.0.0-2041.jar
drwxr-xr-x  3 root root      4096 Jul  7 21:00 lib/
drwxr-xr-x  2 root root      4096 Jul  7 19:27 libexec/
drwxr-xr-x  3 root root      4096 Jul  7 19:27 man/
-rw-r--r--  1 root root 191351259 Nov 20  2014 mapreduce.tar.gz
drwxr-xr-x  2 root root      4096 Jul  7 19:27 sbin/
drwxr-xr-x  3 root root      4096 Jul  7 19:27 share/


==========================


Hope the path are correct..

**Comment by mikehomee** [comment]
One more question, what are these machines?
hibench.masters.hostnames and hibench.slaves.hostnames?

We do have 2 ResourceManagers (HA) and 34 NodeManagers

**Comment by mikehomee** [comment]
From the machine where I run HiBench, do I need to have an ssh (password-less) access to all nodes?

**Comment by GayathriMurali** [comment]
Are you running in Yarn mode? Looks like this is an issue with cluster config. Can you post your settings for HDFS master and Spark master?

**Comment by mikehomee** [comment]
I doubled checked it, and it's looks like im running in Yarn mode. Already disabled yarn mode. And prompt me a new error..
queue name: default.

Im using yarn scheduler and remove the default queue name, https://github.com/intel-hadoop/HiBench/issues/139

Any help on how to add queuename?

**Comment by dkhungme** [comment]
I am facing similar problem and received "prepared failed" message. Any help please?

Thanks

**Comment by mikehomee** [comment]
@dkhungme, I just disabled yarn mode.

#hibench.spark.master		yarn-client

Hope that helps..

**Comment by dkhungme** [comment]
@mikehomee thanks much buddy. This resolves the problem.

**Comment by lvsoft** [comment]
Disable yarn mode by comment out this line will fallback to `local[1]`, which is basically local mode with only 1 thread.

According to you description, seems like the execution of `yarn node -list` is too slow. Can you confirm that by execute `bin/yarn node -list` under your yarn home?

**Comment by islamzee** [comment]
I am having the exact same problem. I have HDP running, as checked from running jps. 
Same error. I have been on the run behind this error for a month now, and I don't get a stable solution

**Comment by asarraf** [comment]
I am using Cloudera Quickstart VM. The way I was able to fix it was by adding 2 parameters in the hibench.conf (This file is present in the $HIBENCH_HOME/conf/)
hibench.masters.hostnames cloudera.quickstart
hibench.slaves.hostnames cloudera.quickstart

To customize for the specific cluster, use the respective values of hostname for master and slave nodes, respectively. Hope that helps.

**Comment by adepusreelakshmi** [comment]
I got the same problem for hadoop benchmarks .I resolved the same problem by manually setting master and slave hostname in hibench.conf file and the port number that i specified for hdfs in core-site.xml of hadoop installation was different from the default one 8020 given in hadoop.conf file of hibench.I corrected the port number and it was working fine
