### ISSUE TITLE
Regular expression issues on yarn-site.xml

### ISSUE THREAD

**Issue by lee212** [intel-hadoop/HiBench#137]
Hi,

My yarn-site.xml looks like:
```
<configuration>
<property>
<name>yarn.resourcemanager.hostname</name>
<value>master</value>
<description>The hostname of the ResourceManager</description>
</property>
<property>
<name>yarn.nodemanager.aux-services</name>
<value>mapreduce_shuffle</value>
<description>shuffle service for MapReduce</description>
</property>
</configuration>
```

It is not parsed when I run "run-all.sh". the error messages:

```
# ./run-all.sh
Prepare aggregation ...
Exec script: /HiBench/workloads/aggregation/prepare/prepare.sh
Parsing conf: /HiBench/conf/00-default-properties.conf
Parsing conf: /HiBench/conf/10-data-scale-profile.conf
Parsing conf: /HiBench/conf/99-user_defined_properties.conf
Parsing conf: /HiBench/workloads/aggregation/conf/00-aggregation-default.conf
Parsing conf: /HiBench/workloads/aggregation/conf/10-aggregation-userdefine.conf
Traceback (most recent call last):
  File "/HiBench/bin/functions/load-config.py", line 448, in <module>
    load_config(conf_root, workload_root, workload_folder)
  File "/HiBench/bin/functions/load-config.py", line 154, in load_config
    generate_optional_value()
  File "/HiBench/bin/functions/load-config.py", line 366, in generate_optional_value
    assert 0, "Get workers from yarn web UI page failed, reason:%s\nplease set `hibench.masters.hostnames` and `hibench.slaves.hostnames` manually" % e
AssertionError: Get workers from yarn web UI page failed, reason:Unknown resourcemanager, please check `hibench.hadoop.configure.dir` and "yarn-site.xml" file
please set `hibench.masters.hostnames` and `hibench.slaves.hostnames` manually
/HiBench/bin/functions/workload-functions.sh: line 33: .: filename argument required
.: usage: . filename [arguments]
start HadoopPrepareAggregation bench
/HiBench/workloads/aggregation/prepare/prepare.sh: line 25: INPUT_HDFS: unbound variable
ERROR: aggregation prepare failed!
```

I looked the ```HiBench/bin/functions/load-config.py``` file and your regular expression for yarn.resourcemanager.hostname (line 359, 360) requires port number along with a hostname like localhost:8032 which mine doesn't have.

Should I place a port number like yarn.resourcemanager.address? I'm afraid it breaks running YARN if I add a port number. Also, I'd like to run HiBench with ResourceManagers (HA) but I am not sure the yarn-site.xml can be parsed because the configuration has different properties according to https://hadoop.apache.org/docs/current/hadoop-yarn/hadoop-yarn-site/ResourceManagerHA.html

**Comment by GayathriMurali** [comment]
can you please post your HDFS master and Spark master setting?

**Comment by robert-schmidtke** [comment]
There were multiple issues with this that I ran into as well, among them the described required port, but also multiple ```f.read()``` calls which just return the empty string after the file is read for the first time. I've opened a PR that addresses these issues, and fixes them for me at least: #176
