### ISSUE TITLE
 ERROR scheduler.TaskSetManager: Task 0 in stage 1723.0 failed 4 times; aborting job

### ISSUE THREAD

**Issue by DonaldLiujie** [intel-hadoop/HiBench#156]
I got the error message when I run streaming benchmark. I run workload/streamingbench/spark/bin/run.sh and get the following logs:
/**********************************************************************************************/
15/11/27 15:47:30 INFO scheduler.DAGScheduler: Stage 1747 (foreachRDD at IdentityJob.scala:27) finished in 0.022 s
15/11/27 15:47:30 INFO cluster.YarnClientClusterScheduler: Removed TaskSet 1747.0, whose tasks have all completed, from pool
15/11/27 15:47:30 INFO scheduler.DAGScheduler: Job 1747 finished: foreachRDD at IdentityJob.scala:27, took 0.027243 s
15/11/27 15:47:30 INFO scheduler.JobScheduler: Finished job streaming job 1448610450000 ms.0 from job set of time 1448610450000 ms
15/11/27 15:47:30 INFO scheduler.JobScheduler: Total delay: 0.038 s for time 1448610450000 ms (execution: 0.030 s)
15/11/27 15:47:30 INFO rdd.MappedRDD: Removing RDD 3493 from persistence list
LatencyController: total records:0 Receivers:0
15/11/27 15:47:30 INFO storage.BlockManager: Removing RDD 3493
15/11/27 15:47:30 INFO kafka.KafkaRDD: Removing RDD 3492 from persistence list
15/11/27 15:47:30 INFO storage.BlockManager: Removing RDD 3492
15/11/27 15:47:30 INFO scheduler.ReceivedBlockTracker: Deleting batches ArrayBuffer()
/**********************************************************************************************/

Then I run worload/streamingbench/prepare/gendata.sh after I run initTopic.sh and genSeedDataset.sh. I think this can start sending data to the benchmark. I get some exceptions and errors:

/**********************************************************************************************/
[2015-11-27 15:43:30,003] INFO Closing socket connection to /10.0.3.90. (kafka.network.Processor)
[2015-11-27 15:43:30,006] INFO Closing socket connection to /10.0.3.90. (kafka.network.Processor)
15/11/27 15:43:30 INFO scheduler.JobScheduler: Added jobs for time 1448610210000 ms
15/11/27 15:43:30 INFO scheduler.JobScheduler: Starting job streaming job 1448610210000 ms.0 from job set of time 1448610210000 ms
15/11/27 15:43:30 INFO spark.SparkContext: Starting job: foreachRDD at IdentityJob.scala:27
15/11/27 15:43:30 INFO scheduler.DAGScheduler: Got job 1723 (foreachRDD at IdentityJob.scala:27) with 1 output partitions (allowLocal=false)
15/11/27 15:43:30 INFO scheduler.DAGScheduler: Final stage: Stage 1723(foreachRDD at IdentityJob.scala:27)
15/11/27 15:43:30 INFO scheduler.DAGScheduler: Parents of final stage: List()
15/11/27 15:43:30 INFO scheduler.DAGScheduler: Missing parents: List()
15/11/27 15:43:30 INFO scheduler.DAGScheduler: Submitting Stage 1723 (MappedRDD[3447] at map at RunBenchWithInit.scala:52), which has no missing parents
15/11/27 15:43:30 INFO storage.MemoryStore: ensureFreeSpace(2880) called with curMem=683417, maxMem=2223023063
15/11/27 15:43:30 INFO storage.MemoryStore: Block broadcast_1723 stored as values in memory (estimated size 2.8 KB, free 2.1 GB)
15/11/27 15:43:30 INFO storage.MemoryStore: ensureFreeSpace(2863) called with curMem=686297, maxMem=2223023063
15/11/27 15:43:30 INFO storage.MemoryStore: Block broadcast_1723_piece0 stored as bytes in memory (estimated size 2.8 KB, free 2.1 GB)
15/11/27 15:43:30 INFO storage.BlockManagerInfo: Added broadcast_1723_piece0 in memory on lxc-jie-0:46133 (size: 2.8 KB, free: 2.1 GB)
15/11/27 15:43:30 INFO storage.BlockManagerMaster: Updated info of block broadcast_1723_piece0
15/11/27 15:43:30 INFO spark.SparkContext: Created broadcast 1723 from getCallSite at DStream.scala:294
15/11/27 15:43:30 INFO scheduler.DAGScheduler: Submitting 1 missing tasks from Stage 1723 (MappedRDD[3447] at map at RunBenchWithInit.scala:52)
15/11/27 15:43:30 INFO cluster.YarnClientClusterScheduler: Adding task set 1723.0 with 1 tasks
15/11/27 15:43:30 INFO scheduler.TaskSetManager: Starting task 0.0 in stage 1723.0 (TID 1933, lxc-jie-0, NODE_LOCAL, 1375 bytes)
15/11/27 15:43:30 INFO storage.BlockManagerInfo: Added broadcast_1723_piece0 in memory on lxc-jie-0:44729 (size: 2.8 KB, free: 2.1 GB)
15/11/27 15:43:30 WARN scheduler.TaskSetManager: Lost task 0.0 in stage 1723.0 (TID 1933, lxc-jie-0): org.apache.spark.util.TaskCompletionListenerException
        at org.apache.spark.TaskContextImpl.markTaskCompleted(TaskContextImpl.scala:76)
        at org.apache.spark.scheduler.Task.run(Task.scala:58)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:196)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

15/11/27 15:43:30 INFO scheduler.TaskSetManager: Starting task 0.1 in stage 1723.0 (TID 1934, lxc-jie-0, NODE_LOCAL, 1375 bytes)
15/11/27 15:43:30 INFO scheduler.TaskSetManager: Lost task 0.1 in stage 1723.0 (TID 1934) on executor lxc-jie-0: org.apache.spark.util.TaskCompletionListenerException (null) [duplicate 1]
15/11/27 15:43:30 INFO scheduler.TaskSetManager: Starting task 0.2 in stage 1723.0 (TID 1935, lxc-jie-0, NODE_LOCAL, 1375 bytes)
15/11/27 15:43:30 INFO scheduler.TaskSetManager: Lost task 0.2 in stage 1723.0 (TID 1935) on executor lxc-jie-0: org.apache.spark.util.TaskCompletionListenerException (null) [duplicate 2]
15/11/27 15:43:30 INFO scheduler.TaskSetManager: Starting task 0.3 in stage 1723.0 (TID 1936, lxc-jie-0, NODE_LOCAL, 1375 bytes)
15/11/27 15:43:30 INFO scheduler.TaskSetManager: Lost task 0.3 in stage 1723.0 (TID 1936) on executor lxc-jie-0: org.apache.spark.util.TaskCompletionListenerException (null) [duplicate 3]
15/11/27 15:43:30 ERROR scheduler.TaskSetManager: Task 0 in stage 1723.0 failed 4 times; aborting job
15/11/27 15:43:30 INFO cluster.YarnClientClusterScheduler: Removed TaskSet 1723.0, whose tasks have all completed, from pool
15/11/27 15:43:30 INFO cluster.YarnClientClusterScheduler: Cancelling stage 1723
15/11/27 15:43:30 INFO scheduler.DAGScheduler: Job 1723 failed: foreachRDD at IdentityJob.scala:27, took 0.060448 s
15/11/27 15:43:30 ERROR scheduler.JobScheduler: Error running job streaming job 1448610210000 ms.0
org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 1723.0 failed 4 times, most recent failure: Lost task 0.3 in stage 1723.0 (TID 1936, lxc-jie-0): org.apache.spark.util.TaskCompletionListenerException
        at org.apache.spark.TaskContextImpl.markTaskCompleted(TaskContextImpl.scala:76)
        at org.apache.spark.scheduler.Task.run(Task.scala:58)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:196)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

Driver stacktrace:
        at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1214)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1203)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1202)
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
        at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1202)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:696)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:696)
        at scala.Option.foreach(Option.scala:236)
        at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:696)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessActor$$anonfun$receive$2.applyOrElse(DAGScheduler.scala:1420)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessActor.aroundReceive(DAGScheduler.scala:1375)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
        at akka.actor.ActorCell.invoke(ActorCell.scala:487)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
        at akka.dispatch.Mailbox.run(Mailbox.scala:220)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
/**********************************************************************************************/

Could you plealse give some advices?
Thanks,
JIe

**Comment by carsonwang** [comment]
Can you run gendata.sh before starting the spark streaming job?
Please make sure the data are sent to kafka successfully. You can use kafka-console-consumer.sh provided by kafka to confirm this .

**Comment by DonaldLiujie** [comment]
I tried run gendata.sh before starting the streaming job. The error message is the same.
I also tried kafka-console-consumer.sh on local node and I can get the following message:
I guess it is the data produced by gendata.sh,right?
/*******************************************************************************/
363349.90.155.312009-09-10 00:00:000.32065994larxrvaylyapyy
4363323.236.236.241995-07-31 00:00:000.528866larxrvaylyapyyk
4363315.55.247.2431989-09-26 00:00:000.99207366larxrvaylyapy
43633205.160.7.2151994-10-14 00:00:000.38102424larxrvaylyapy
43633172.236.28.1571971-11-05 00:00:000.6174849larxrvaylyapy
43633158.18.91.1422000-08-07 00:00:000.4210267larxrvaylyapyy
4363348.35.12.1911990-11-10 00:00:000.93739414larxrvaylyapyy
4363993.7.69.232010-03-03 00:00:000.1899181rwvzwixvtmswfbhvk
43639126.111.188.1152008-07-13 00:00:000.08036327rwvzwixvtms
43639222.138.38.2412010-07-31 00:00:000.95272607rwvzwixvtmsw
4363967.16.248.1512001-06-28 00:00:000.83946323rwvzwixvtmswf
4363920.61.196.201992-06-08 00:00:000.68608487rwvzwixvtmswfb
436398.4.221.1992001-01-09 00:00:000.109805346rwvzwixvtmswfb
4363960.232.185.1331995-06-30 00:00:000.55792975rwvzwixvtmsw
436391.41.192.2152011-09-03 00:00:000.775126rwvzwixvtmswfbhv
4363977.139.80.371971-02-13 00:00:000.6062921rwvzwixvtmswfbh

**Comment by carsonwang** [comment]
Yes. It seems the data were sent to kafka successfully. On the Spark Web UI/Streaming Tab, did it show any records received?
I am working on some fixes to the streaming bench. You may try later after some issues are fixed.

**Comment by carsonwang** [comment]
@DonaldLiujie , can you try the master branch to see if you have the same issue?
