### ISSUE TITLE
Running  genSeedDataset.sh of streambench hangs.

### ISSUE THREAD

**Issue by ashansa** [intel-hadoop/HiBench#157]
I am trying to run streambench of HiBench 5.0 in linux. When running genSeedDataset.sh, the process hangs with following log messages. And I could observe that the /HiBench/Streaming/Seeds directory in HDFS is empty.
Could you provide any suggestions on this?

vagrant@vm2-hostname:~/HiBench/workloads/streamingbench/prepare$ ./genSeedDataset.sh 
patching args=
Parsing conf: /home/vagrant/HiBench/conf/00-default-properties.conf
Parsing conf: /home/vagrant/HiBench/conf/01-default-streamingbench.conf
Parsing conf: /home/vagrant/HiBench/conf/10-data-scale-profile.conf
Parsing conf: /home/vagrant/HiBench/conf/20-samza-common.conf
Parsing conf: /home/vagrant/HiBench/conf/30-samza-workloads.conf
Parsing conf: /home/vagrant/HiBench/conf/99-user_defined_properties.conf
Parsing conf: /home/vagrant/HiBench/workloads/streamingbench/conf/00-streamingbench.conf
Parsing conf: /home/vagrant/HiBench/workloads/streamingbench/conf/10-streamingbench-userdefine.conf
probe sleep jar: /srv/hadoop/share/hadoop/mapreduce/hadoop-mapreduce-client-jobclient-2.4.0-tests.jar
spark://172.28.128.5:7077 172.28.128.5
start HadoopPrepareDatafile1 bench
hdfs rm -r: /srv/hadoop/bin/hadoop --config /srv/hadoop/etc/hadoop fs -rm -r -skipTrash hdfs://172.28.128.5:8020/HiBench/Streaming
OpenJDK 64-Bit Server VM warning: You have loaded library /srv/hadoop-2.4.0/lib/native/libhadoop.so.1.0.0 which might have disabled stack guard. The VM will try to fix the stack guard now.
15/12/02 00:10:14 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Deleted hdfs://172.28.128.5:8020/HiBench/Streaming
Pages:120000, USERVISITS:1000000
Submit MapReduce Job: /srv/hadoop/bin/hadoop --config /srv/hadoop/etc/hadoop jar /home/vagrant/HiBench/src/autogen/target/autogen-4.0-SNAPSHOT-jar-with-dependencies.jar HiBench.DataGen -t hive -b hdfs://172.28.128.5:8020/HiBench/Streaming -n Seed -m 12 -r 6 -p 120000 -v 1000000
vagrant@vm3-hostname's password: OpenJDK 64-Bit Server VM warning: You have loaded library /srv/hadoop-2.4.0/lib/native/libhadoop.so.1.0.0 which might have disabled stack guard. The VM will try to fix the stack guard now.
15/12/02 00:10:17 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
curIndex: 349, total: 350

Thanks.

**Comment by carsonwang** [comment]
Basically it launches a map reduce job and writes some random data to HDFS. Did you go through https://github.com/intel-hadoop/HiBench/wiki/Getting-Started and make sure all the configurations are set? Were you able to generate data for other workloads?
For streaming bench, you may want to try the latest master branch which includes many bug fixes.

**Comment by ashansa** [comment]
Thank you very much for the details. New documentation added were useful to have a smooth flow and getting rid of the halting issue. But still I get the below error[1] with the original log message I have posted, and the container log of the node says [2]

I suspect that this can be a due to an incompatible version. I have a setup with 
hadoop-2.4.0
spark-1.3.1
zookeeper-3.4.6
kafka-0.8.1.1
As I understood with documentation, above versions are supported. 
Do you have any suggestions on this? Do I need to build HiBench with a specific java or maven version?

My current installations are
java version "1.7.0_85"
OpenJDK Runtime Environment (IcedTea 2.6.1) (7u85-2.6.1-5ubuntu0.12.04.1)

Apache Maven 3.0.4

[1]
15/12/02 17:12:53 WARN mapreduce.JobSubmitter: Hadoop command-line option parsing not performed. Implement the Tool interface and execute your application with ToolRunner to remedy this.
Exception in thread "main" java.io.IOException: Job failed!
        at org.apache.hadoop.util.RunJar.main(RunJar.java:212)
ERROR: Hadoop job /home/vagrant/HiBench/src/autogen/target/autogen-5.0-SNAPSHOT-jar-with-dependencies.jar HiBench.DataGen failed to run successfully.
Hint: You can goto /home/vagrant/HiBench/report/streamingbench/prepare/conf/../bench.log to check for detailed log.
Opening log tail for you:

	at HiBench.HiveData.createRankingsTableDirectly(HiveData.java:358)
	at HiBench.HiveData.generate(HiveData.java:618)
	at HiBench.DataGen.run(DataGen.java:19)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
	at HiBench.DataGen.main(DataGen.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:212)


===========

[2]
Exception in thread "main" java.lang.IncompatibleClassChangeError: Implementing class
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2625)
	at java.lang.Class.getMethod0(Class.java:2866)
	at java.lang.Class.getMethod(Class.java:1676)
	at sun.launcher.LauncherHelper.getMainMethod(LauncherHelper.java:494)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:486)

Thank You.

**Comment by qiansl127** [comment]
Could you please display entire exception log in `/home/vagrant/HiBench/report/streamingbench/prepare/conf/../bench.log`

**Comment by ashansa** [comment]
Please find the log below.

OpenJDK 64-Bit Server VM warning: You have loaded library /srv/hadoop-2.4.0/lib/native/libhadoop.so.1.0.0 which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
15/12/02 17:33:21 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
mvlbhs
rvqsxngcqzi
xrdcjezwi
mnwbxgwnmeytcfyug
xunkgcl
hsrzjtxqdiwj
pdmdqfoamu
qavxdwdsh
.......... (lot more records like this)
..........
owknycxgcaiv
bwrurqutkcblty
rwrdyxim
ysgfgzmlsofdfjfd
zawvcjfzmzqkmvdi
oigd
curIndex: 349, total: 350
15/12/02 17:33:23 WARN mapreduce.JobSubmitter: Hadoop command-line option parsing not performed. Implement the Tool interface and execute your application with ToolRunner to remedy this.
Exception in thread "main" java.io.IOException: Job failed!
        at org.apache.hadoop.mapred.JobClient.runJob(JobClient.java:836)
        at HiBench.HiveData.createRankingsTableDirectly(HiveData.java:358)
        at HiBench.HiveData.generate(HiveData.java:618)
        at HiBench.DataGen.run(DataGen.java:19)
        at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
        at HiBench.DataGen.main(DataGen.java:45)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.hadoop.util.RunJar.main(RunJar.java:212)

Thank You.

**Comment by ashansa** [comment]
Attaching the log file with all entries.
[bench.log.txt](https://github.com/intel-hadoop/HiBench/files/50907/bench.log.txt)

**Comment by ashansa** [comment]
The issue was in autogen module. It was referring hadoop-core which is not available in hadoop 2.4
I had to replace hadoop-core dependency with hadoop-common and hadoop-client.

And org.apache.mahout was binding a hadoop-core 1.x version and that also had to be excluded from org.apache.mahout dependency for HiBench to work with hadoop 2.x for my usecase.

**Comment by carsonwang** [comment]
Thanks for the update @ashansa , glad to know that you resolved the issue.
I just want to understand further how you encounter this issue because I did not see the same issue when using hadoop 2.x. How did you build HiBench? Did you use the `bin/build-all.sh`? If you manually build it, did you specify `-D MR2`? i.e. `mvn clean package -D spark1.3 -D MR2`. We also just fixed another bug in `build-all.sh`.

**Comment by ashansa** [comment]
I built HiBench manually using the below command and was trying to run streamingbench with the build.
        mvn clean package -D spark1.3 -D MR2

Yes, it is interesting to understand how the autogen jar works with hadoop 2.x.  Because in my original build, it had a hadoop-core dependency with the version hadoop.mr1.version and when I check the maven dependency tree, mahout too was binding a hadoop-core 1.x version there.

May be we can search for the hadoop-core version in your autogen build too to understand this.

**Comment by rajatma1993** [comment]
I am facing the similar error when I am running genseedDataset.sh when trying to generate the Data for the Flinkbench(Identity), Below are Versions I am using.

Hadoop - 2.4
Kafka - 0.8.2.2
Scala - 2.10 
Flink - 1.0.3 
Java - 8 
Hive - 4.0.0 

Below is log file.
[bench.log.txt](https://github.com/user-attachments/files/17977232/bench.log.txt)

I have tried the option suggested by the @ashansa ,But It did not help me.

Could you please help.
