### ISSUE TITLE
Error occurs when testing streamingbench on kerberized kafka/spark 1.5

### ISSUE THREAD

**Issue by yangzq** [intel-hadoop/HiBench#182]
I am wondering whether streamingbench in hibench v5.0 supports kerberized kafka/spark 1.5 cluster? Are there any tests/implements or documents on this scenario? I am doing some tests on this and some errors occurred, finding nothing about this scenario in project wiki. Project denpends on kafka-client 0.8.1, which does not support kerberos according to apache.org.
using kafka 0.9.0.0, spark 1.5.0 and hadoop 2.6.0-cdh5.5.0
Exception as follows:

> Exception in thread "main" org.apache.kafka.common.config.ConfigException: Missing required configuration "bootstrap.servers" which has no default value.
        at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:148)
        at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:49)
        at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:56)
        at org.apache.kafka.clients.producer.ProducerConfig.<init>(ProducerConfig.java:317)
        at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:181)
        at com.intel.hibench.streambench.NewKafkaConnector.<init>(NewKafkaConnector.java:47)
        at com.intel.hibench.streambench.StartNew.main(StartNew.java:58)

**Comment by yangzq** [comment]
After modifying some code to use kafka-clients-0.9.0.0, the problem is solved.
