### ISSUE TITLE
StreamingBench question

### ISSUE THREAD

**Issue by barrenlake** [intel-hadoop/HiBench#183]
hello,  i run hibench as "Getting Started for StreamingBench" describe at the step.7
     (1)workloads/stremingbench/prepare/initTopics.sh
     (2)workloads/stremingbench/prepare/genSeedDataset.sh
     (3)workloads/stremingbench/prepare/gendata.sh

when i exec (3) , But i receive this error:

Exception in thread "Timer-0" java.lang.ArrayIndexOutOfBoundsException: 4
        at com.intel.hibench.streambench.NewKafkaConnector.parseUserVisitTable(NewKafkaConnector.java:120)
        at com.intel.hibench.streambench.NewKafkaConnector.publishData(NewKafkaConnector.java:74)
        at com.intel.hibench.streambench.NewKafkaConnector.publishDataSlice(NewKafkaConnector.java:161)
        at com.intel.hibench.streambench.StartPeriodic$SendTask.run(StartPeriodic.java:94)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)_

finish StreamingBenchPrepare bench

please check

**Comment by jiaqianjing** [comment]
@barrenlake  Have you fixed it? I had this problem,too.
