### ISSUE TITLE
nutchindexing mapreduce Indexer failing with NoSuchMethodError

### ISSUE THREAD

**Issue by ChristianStier** [intel-hadoop/HiBench#263]
Running the Nutch Indexing MapReduce Workload I get the following error message in the individual MR jobs (content of stderr from the application*/container* folder):
```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/christian/Programs/hadoop-2.7.2/share/hadoop/common/lib/slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/tmp/hadoop-christian/nm-local-dir/usercache/christian/appcache/application_1471338246859_0003/filecache/10/job.jar/lib/slf4j-log4j12-1.4.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]

Exception: java.lang.NoSuchMethodError thrown from the UncaughtExceptionHandler in thread "main"
```

This occurs within the execution of the nutchindexing MapReduce job:
```
16/08/16 11:11:53 INFO indexer.Indexer: Indexer: starting at 2016-08-16 11:11:53
16/08/16 11:11:53 INFO indexer.IndexerMapReduce: IndexerMapReduce: crawldb: hdfs://localhost/HiBench/Nutchindexing/Input/crawldb
16/08/16 11:11:53 INFO indexer.IndexerMapReduce: IndexerMapReduce: linkdb: hdfs://localhost/HiBench/Nutchindexing/Input/linkdb
16/08/16 11:11:53 INFO indexer.IndexerMapReduce: IndexerMapReduces: adding segment: hdfs://localhost/HiBench/Nutchindexing/Input/segments/*
16/08/16 11:11:54 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
16/08/16 11:11:55 INFO client.RMProxy: Connecting to ResourceManager at localhost/127.0.0.1:8032
16/08/16 11:11:55 INFO client.RMProxy: Connecting to ResourceManager at localhost/127.0.0.1:8032
16/08/16 11:11:56 INFO mapred.FileInputFormat: Total input paths to process : 54
16/08/16 11:11:57 INFO mapreduce.JobSubmitter: number of splits:54
16/08/16 11:11:57 INFO mapreduce.JobSubmitter: Submitting tokens for job: job_1471338246859_0006
16/08/16 11:11:57 INFO impl.YarnClientImpl: Submitted application application_1471338246859_0006
16/08/16 11:11:57 INFO mapreduce.Job: The url to track the job: http://christian:8088/proxy/application_1471338246859_0006/
16/08/16 11:11:57 INFO mapreduce.Job: Running job: job_1471338246859_0006
16/08/16 11:12:04 INFO mapreduce.Job: Job job_1471338246859_0006 running in uber mode : false
16/08/16 11:12:04 INFO mapreduce.Job:  map 0% reduce 0%
16/08/16 11:12:04 INFO mapreduce.Job: Job job_1471338246859_0006 failed with state FAILED due to: Application application_1471338246859_0006 failed 2 times due to AM Container for appattempt_1471338246859_0006_000002 exited with  exitCode: 1
For more detailed output, check application tracking page:http://christian:8088/cluster/app/application_1471338246859_0006Then, click on links to logs of each attempt.
Diagnostics: Exception from container-launch.
Container id: container_1471338246859_0006_02_000001
Exit code: 1
Stack trace: ExitCodeException exitCode=1:
	at org.apache.hadoop.util.Shell.runCommand(Shell.java:545)
	at org.apache.hadoop.util.Shell.run(Shell.java:456)
	at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:722)
	at org.apache.hadoop.yarn.server.nodemanager.DefaultContainerExecutor.launchContainer(DefaultContainerExecutor.java:212)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:302)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:82)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)


Container exited with a non-zero exit code 1
Failing this attempt. Failing the application.
16/08/16 11:12:05 INFO mapreduce.Job: Counters: 0
16/08/16 11:12:05 FATAL indexer.Indexer: Indexer: java.io.IOException: Job failed!
	at org.apache.hadoop.mapred.JobClient.runJob(JobClient.java:865)
	at org.apache.nutch.indexer.Indexer.index(Indexer.java:76)
	at org.apache.nutch.indexer.Indexer.run(Indexer.java:97)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
	at org.apache.nutch.indexer.Indexer.main(Indexer.java:106)

```

I would greatly appreciate any pointers what might be causing this.

Thanks,
Christian

**Comment by carsonwang** [comment]
Thanks for reporting the issue, @ChristianStier . This was just fixed by #303 .
Please make sure `zip` is installed before running the workload.
Please report back if the issue still exist.
