### ISSUE TITLE
hibench.hadoop.examples.jar Path error on automatically installed CDH deployment

### ISSUE THREAD

**Issue by biaobean** [intel-hadoop/HiBench#301]
In the bin/functions/load-config.py file, the hibench.hadoop.examples.jar is located by:

HibenchConf["hibench.hadoop.examples.jar"] = OneAndOnlyOneFile(HibenchConf['hibench.hadoop.mapreduce.home'] + "/share/hadoop/mapreduce2/hadoop-mapreduce-examples-*.jar")

While there's no such "share/hadoop/mapreduce2/" path when using CDH installed by Cloudera parcel. The correct path is:

HibenchConf["hibench.hadoop.examples.jar"] = OneAndOnlyOneFile(HibenchConf['hibench.hadoop.mapreduce.home'] + "/../../jars/hadoop-mapreduce-examples-*.jar")

I'd like to suggest to find examples.jar only when not set by user. Thus, we can input the customized examples.jar path instead of modify the shell code.

**Comment by akaito1412** [comment]
Thank you, I face this issue cause I installed by cloudera parcel.

**Comment by carsonwang** [comment]
HiBench doesn't do well to auto probe the example jar for CDH. Please manually configure `hibench.hadoop.examples.jar` to the correct path in 99-user_defined_properties.conf.

**Comment by akaito1412** [comment]
@carsonwang  I already manually configure in 99-user_defined_properties.conf, but the issue still happen. 
I change the load-config.py in the line of hibench hadoop examples jar, and it's working. 
So, am I allowed to change the load-config.py ? I mean, if I change it, is that any problem when I running HiBench ?

**Comment by carsonwang** [comment]
What did you set to `hibench.hadoop.examples.jar` and is it the correct path for the example jar? If it is set, load-config.py should not probe it again.

**Comment by akaito1412** [comment]
@carsonwang I;m sorry, it's my bad to not set the hibench.hadoop.examples.jar correctly. so that's why the issue come from. I already bringing back the original load-config.py and correct the hibench.hadoop.examples.jar and it's working, but I got other problem like this 

[root@master1 HiBench-master]# workloads/wordcount/prepare/prepare.sh 
patching args=
Parsing conf: /root/HiBench-master/conf/00-default-properties.conf
Parsing conf: /root/HiBench-master/conf/01-default-streamingbench.conf
Parsing conf: /root/HiBench-master/conf/10-data-scale-profile.conf
Parsing conf: /root/HiBench-master/conf/20-samza-common.conf
Parsing conf: /root/HiBench-master/conf/30-samza-workloads.conf
Parsing conf: /root/HiBench-master/conf/99-user_defined_properties.conf
Parsing conf: /root/HiBench-master/workloads/wordcount/conf/00-wordcount-default.conf
Parsing conf: /root/HiBench-master/workloads/wordcount/conf/10-wordcount-userdefine.conf
Probing spark verison, may last long at first time...
probe sleep jar: /usr/lib/hadoop-mapreduce/hadoop-mapreduce-client-jobclient-tests.jar
Traceback (most recent call last):
  File "/root/HiBench-master/bin/functions/load-config.py", line 556, in <module>
    load_config(conf_root, workload_root, workload_folder, patching_config)
  File "/root/HiBench-master/bin/functions/load-config.py", line 161, in load_config
    generate_optional_value()
  File "/root/HiBench-master/bin/functions/load-config.py", line 460, in generate_optional_value
    assert 0, "Get workers from yarn web UI page failed, reason:%s\nplease set `hibench.masters.hostnames` and `hibench.slaves.hostnames` manually" % e
AssertionError: Get workers from yarn web UI page failed, reason:[Errno 20] Not a directory: '/usr/bin/hadoop/etc/hadoop/yarn-site.xml'
please set `hibench.masters.hostnames` and `hibench.slaves.hostnames` manually
/root/HiBench-master/bin/functions/workload-functions.sh: line 39: .: filename argument required
.: usage: . filename [arguments]
start HadoopPrepareWordcount bench
workloads/wordcount/prepare/prepare.sh: line 25: INPUT_HDFS: unbound variable

Do you know what happen is this ?

**Comment by carsonwang** [comment]
Is `hibench.hadoop.executable` correctly set? `/usr/bin/hadoop` is likely the correct value in your environment?

**Comment by akaito1412** [comment]
@carsonwang I think is yes, but i'm not sure so this is my 99-user_defined_properties.conf, if you mind to check it. 

# Hadoop home
hibench.hadoop.home             /usr/bin/hadoop

# Spark home
hibench.spark.home              /PART/TO/YOUR/SPARK/ROOT

# HDFS master, set according to hdfs-site.xml
hibench.hdfs.master             hdfs://localhost:8022

# Spark master
#   standalone mode: `spark://xxx:7077`
#   YARN mode: `yarn-client`
#   unset: fallback to `local[1]`
hibench.spark.master            yarn-client

#======================================================
# Not mandatory but important settings
#======================================================

# `hibench.hadoop.executable` is used to auto probe hadoop version and
# hadoop release, which is critical for further configurations. Most
# cases `hadoop` executable be placed under HADOOP_HOME/bin. However,
# in some cases such as CDH?/MR1, it must be explicitly defined:

hibench.hadoop.executable       ${hibench.hadoop.home}/bin-mapreduce1/hadoop
hibench.hadoop.mapreduce.home   /usr/lib/hadoop-mapreduce

# `hibench.hadoop.version` will be auto probed according to
# `hibench.hadoop.executable` version information report. However, for
# CDH release, both `hadoop version` of MR1 and MR2 will produce same
# report, which can't probe right MR versions. You'll need to
# explicitly define MR versions here.

hibench.hadoop.version          hadoop2
hibench.hadoop.release          hdp

# `hibench.spark.version` is used to choose which sparkbench workload
# jar. Mostly situation it'll be auto probed. Please override if spark
# version is not probed correctly. For spark version after 1.6, please
# set it to spark1.6
# Note, supported values: `spark1.2` to `spark1.6`

#hibench.spark.version          spark1.6

#======================================================
# Optional settings
#======================================================

hibench.hadoop.examples.jar     /usr/lib/hadoop-mapreduce/hadoop-mapreduce-examples-*.jar

actually, I'm sorry if I asking a lot, cause I'm a newbie in a hadoop, I did this because I have a work from my lecturer to do a benchmarking hadoop cluster using a HiBench.  
I'm not sure if the hibench.hadoop.home is correct path, cause I just set the path using command 

[root@master1 HiBench-master]# which hadoop
/usr/bin/hadoop

**Comment by akaito1412** [comment]
@carsonwang yes thank you, I already fix that problem, the hibench.hadoop.executable is not correctly set. but I'm not sure about this error message 
> AssertionError: Get workers from yarn web UI page failed, reason:[Errno 20] Not a directory: 
> '/usr/bin/hadoop/etc/hadoop/yarn-site.xml'

because I think the path of yarn-site.xml is not right, the right pah is at /etc/hadoop/conf/yarn-site.xml
So, am I must be worried about that ? 

and I got other problem when I running the wordcount like this 
> Parsing conf: /root/HiBench-master/conf/00-default-properties.conf
Parsing conf: /root/HiBench-master/conf/01-default-streamingbench.conf
Parsing conf: /root/HiBench-master/conf/10-data-scale-profile.conf
Parsing conf: /root/HiBench-master/conf/20-samza-common.conf
Parsing conf: /root/HiBench-master/conf/30-samza-workloads.conf
Parsing conf: /root/HiBench-master/conf/99-user_defined_properties.conf
Parsing conf: /root/HiBench-master/workloads/wordcount/conf/00-wordcount-default.conf
Parsing conf: /root/HiBench-master/workloads/wordcount/conf/10-wordcount-userdefine.conf
Probing spark verison, may last long at first time...
probe sleep jar: /usr/lib/hadoop-mapreduce/hadoop-mapreduce-client-jobclient-tests.jar
ERROR, execute cmd: '( /usr/bin/yarn node -list 2> /dev/null | grep RUNNING )' timedout.
  STDOUT:

>  STDERR:
Please check!
Traceback (most recent call last):
  File "/root/HiBench-master/bin/functions/load-config.py", line 556, in <module>
    load_config(conf_root, workload_root, workload_folder, patching_config)
  File "/root/HiBench-master/bin/functions/load-config.py", line 161, in load_config
    generate_optional_value()
  File "/root/HiBench-master/bin/functions/load-config.py", line 460, in generate_optional_value
    assert 0, "Get workers from yarn web UI page failed, reason:%s\nplease set `hibench.masters.hostnames` and `hibench.slaves.hostnames` manually" % e
AssertionError: Get workers from yarn web UI page failed, reason:( /usr/bin/yarn node -list 2> /dev/null | grep RUNNING ) executed timedout for 5 seconds
please set `hibench.masters.hostnames` and `hibench.slaves.hostnames` manually
/root/HiBench-master/bin/functions/workload-functions.sh: line 39: .: filename argument required
.: usage: . filename [arguments]
start HadoopPrepareWordcount bench
workloads/wordcount/prepare/prepare.sh: line 25: INPUT_HDFS: unbound variable

**Comment by mliwang** [comment]
I meet the same proplem.And I got the problem when I run prepare.sh like this:
patching args=
Parsing conf: /usr/spark/HiBench-HiBench-6.0/conf/hadoop.conf
Parsing conf: /usr/spark/HiBench-HiBench-6.0/conf/hibench.conf
Parsing conf: /usr/spark/HiBench-HiBench-6.0/conf/spark.conf
Parsing conf: /usr/spark/HiBench-HiBench-6.0/conf/workloads/micro/wordcount.conf
probe sleep jar: /usr/spark/hadoop/share/hadoop/mapreduce/hadoop-mapreduce-client-jobclient-2.7.3-tests.jar
ERROR, execute cmd: '( /usr/spark/hadoop/bin/yarn node -list 2> /dev/null | grep RUNNING )' timedout.
  STDOUT:

  STDERR:

  Please check!
Traceback (most recent call last):
  File "/usr/spark/HiBench-HiBench-6.0/bin/functions/load_config.py", line 712, in <module>
    load_config(conf_root, workload_configFile, workload_folder, patching_config)
  File "/usr/spark/HiBench-HiBench-6.0/bin/functions/load_config.py", line 217, in load_config
    generate_optional_value()
  File "/usr/spark/HiBench-HiBench-6.0/bin/functions/load_config.py", line 640, in generate_optional_value
    probe_masters_slaves_hostnames()
  File "/usr/spark/HiBench-HiBench-6.0/bin/functions/load_config.py", line 576, in probe_masters_slaves_hostnames
    probe_masters_slaves_by_Yarn()
  File "/usr/spark/HiBench-HiBench-6.0/bin/functions/load_config.py", line 528, in probe_masters_slaves_by_Yarn
    assert 0, "Get workers from yarn-site.xml page failed, reason:%s\nplease set `hibench.masters.hostnames` and `hibench.slaves.hostnames` manually" % e
AssertionError: Get workers from yarn-site.xml page failed, reason:( /usr/spark/hadoop/bin/yarn node -list 2> /dev/null | grep RUNNING ) executed timedout for 5 seconds
please set `hibench.masters.hostnames` and `hibench.slaves.hostnames` manually
/usr/spark/HiBench-HiBench-6.0/bin/functions/workload-functions.sh: line 38: .: filename argument required
.: usage: . filename [arguments]
start HadoopPrepareWordcount bench
./prepare.sh: line 26: INPUT_HDFS: unbound variable


I had set 
hibench.masters.hostnames localhost
hibench.slaves.hostnames localhost

in my hibench.conf,but it doesn't work.

when I run prepare.sh on other machine,It can works well,but I run run.sh frequently,I always got  OUTPUT_HDFS: unbound variable

**Comment by ruhan09** [comment]
bin/workloads/micro/wordcount/prepare/prepare.sh
patching args=
Parsing conf: /HiBench/conf/hadoop.conf
Parsing conf: /HiBench/conf/hibench.conf
Parsing conf: /HiBench/conf/workloads/micro/wordcount.conf
Traceback (most recent call last):
File "/HiBench/bin/functions/load_config.py", line 713, in <module>
load_config(conf_root, workload_configFile, workload_folder, patching_config)
File "/HiBench/bin/functions/load_config.py", line 217, in load_config
generate_optional_value()
File "/HiBench/bin/functions/load_config.py", line 636, in generate_optional_value
probe_hadoop_examples_jars()
File "/HiBench/bin/functions/load_config.py", line 409, in probe_hadoop_examples_jars
examples_jars_candidate_list, "hibench.hadoop.examples.jar")
File "/HiBench/bin/functions/load_config.py", line 127, in exactly_one_file
assert 0, "No files found under certain path(s), please set `" + config_name + "` manually"
AssertionError: No files found under certain path(s), please set `hibench.hadoop.examples.jar` manually
/HiBench/bin/functions/workload_functions.sh: line 38: .: filename argument required
.: usage: . filename [arguments]
start HadoopPrepareWordcount bench
bin/workloads/micro/wordcount/prepare/prepare.sh: line 26: INPUT_HDFS: unbound variable

**Comment by ZakiHe** [comment]
@ruhan09 I meet the same problem. And here is my configure.
# Hadoop home
hibench.hadoop.home     /PATH/TO/YOUR/HADOOP/ROOT

# The path of hadoop executable
hibench.hadoop.executable     /usr/bin/hadoop

# Hadoop configraution directory
hibench.hadoop.configure.dir  /etc/hadoop/3.1.0.0-78/0

# The root HDFS path to store HiBench data
hibench.hdfs.master       hdfs://master:8020


# Hadoop release provider. Supported value: apache, cdh5, hdp
hibench.hadoop.release    hdp

**Comment by mark-i-m** [comment]
@ruhan09 I just ran into this, and in my case it was a type in my `hibench.hadoop.home` setting in `conf/hadoop.conf`.
