### ISSUE TITLE
ERROR: Hadoop job ... failed to run successfully.

### ISSUE THREAD

**Issue by akaito1412** [intel-hadoop/HiBench#309]
Hi, 
I will running a first try  benchmarking using HiBench on a Hadoop 2.6.0 with CDH. I'm installing hadoop cluster using a cloudera packages. when I'll do my first run like in a Guide Start, this issue is happen. 
Can anybody tell me why ? 
Thank you for your attention

> [root@master1 HiBench-master]# workloads/wordcount/prepare/prepare.sh 
patching args=
Parsing conf: /root/HiBench-master/conf/00-default-properties.conf
Parsing conf: /root/HiBench-master/conf/01-default-streamingbench.conf
Parsing conf: /root/HiBench-master/conf/10-data-scale-profile.conf
Parsing conf: /root/HiBench-master/conf/20-samza-common.conf
Parsing conf: /root/HiBench-master/conf/30-samza-workloads.conf
Parsing conf: /root/HiBench-master/conf/99-user_defined_properties.conf
Parsing conf: /root/HiBench-master/workloads/wordcount/conf/00-wordcount-default.conf
Parsing conf: /root/HiBench-master/workloads/wordcount/conf/10-wordcount-userdefine.conf
Probing spark verison, may last long at first time...
probe sleep jar: /usr/lib/hadoop-mapreduce/hadoop-mapreduce-client-jobclient-tests.jar
start HadoopPrepareWordcount bench
hdfs rm -r: /usr/bin/hadoop --config /usr/bin/hadoop/etc/hadoop fs -rm -r -skipTrash hdfs://10.5.1.160:50070//HiBench/Wordcount/Input
Error: Cannot find configuration directory: /usr/bin/hadoop/etc/hadoop

> Submit MapReduce Job: /usr/bin/hadoop --config /usr/bin/hadoop/etc/hadoop jar /usr/lib/hadoop-mapreduce/hadoop-mapreduce-examples-2.6.0-cdh5.8.0.jar randomtextwriter -D mapreduce.randomtextwriter.totalbytes=3200000000 -D mapreduce.job.maps=12 -D mapreduce.job.reduces=6 -D mapreduce.output.fileoutputformat.compress=false hdfs://10.5.1.160:50070//HiBench/Wordcount/Input
Error: Cannot find configuration directory: /usr/bin/hadoop/etc/hadoop

> ERROR: Hadoop job /usr/lib/hadoop-mapreduce/hadoop-mapreduce-examples-2.6.0-cdh5.8.0.jar randomtextwriter failed to run successfully.
Hint: You can goto /root/HiBench-master/report/wordcount/prepare/conf/../bench.log to check for detailed log.
Opening log tail for you:

> Error: Cannot find configuration directory: /usr/bin/hadoop/etc/hadoop

I already check the path, but there is no path /usr/bin/hadoop/etc/hadoop on my directory.

**Comment by carsonwang** [comment]
This seems to be another problem in HiBench that fails to auto probe the configuration directory. Please find the correct hadoop configuration directory in your environment and manually set `hibench.hadoop.configure.dir` to it.

**Comment by akaito1412** [comment]
what is the usually default path of the configuration directory on hadoop ?

**Comment by akaito1412** [comment]
I already set the hibench.hadoop.configure.dir. 
but this another error message 

> [root@master1 HiBench-master]# workloads/wordcount/prepare/prepare.sh 
patching args=
Parsing conf: /root/HiBench-master/conf/00-default-properties.conf
Parsing conf: /root/HiBench-master/conf/01-default-streamingbench.conf
Parsing conf: /root/HiBench-master/conf/10-data-scale-profile.conf
Parsing conf: /root/HiBench-master/conf/20-samza-common.conf
Parsing conf: /root/HiBench-master/conf/30-samza-workloads.conf
Parsing conf: /root/HiBench-master/conf/99-user_defined_properties.conf
Parsing conf: /root/HiBench-master/workloads/wordcount/conf/00-wordcount-default.conf
Parsing conf: /root/HiBench-master/workloads/wordcount/conf/10-wordcount-userdefine.conf
Probing spark verison, may last long at first time...
probe sleep jar: /usr/lib/hadoop-mapreduce//hadoop-mapreduce-client-jobclient-tests.jar
start HadoopPrepareWordcount bench
hdfs rm -r: /usr/bin/hadoop --config /etc/hadoop/conf/ fs -rm -r -skipTrash hdfs://10.5.1.160:50070/HiBench/Wordcount/Input
rm: Call From master1/10.5.1.160 to master1:50070 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused

> Submit MapReduce Job: /usr/bin/hadoop --config /etc/hadoop/conf/ jar /usr/lib/hadoop-mapreduce/hadoop-mapreduce-examples-2.6.0-cdh5.8.0.jar randomtextwriter -D mapreduce.randomtextwriter.totalbytes=3200000000 -D mapreduce.job.maps=12 -D mapreduce.job.reduces=6 -D mapreduce.output.fileoutputformat.compress=false hdfs://10.5.1.160:50070/HiBench/Wordcount/Input
16/09/14 14:45:21 WARN security.UserGroupInformation: PriviledgedActionException as:root (auth:SIMPLE) cause:java.net.ConnectException: Call From master1/10.5.1.160 to master1:50070 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
java.net.ConnectException: Call From master1/10.5.1.160 to master1:50070 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
Caused by: java.net.ConnectException: Connection refused
        ... 43 more
ERROR: Hadoop job /usr/lib/hadoop-mapreduce/hadoop-mapreduce-examples-2.6.0-cdh5.8.0.jar randomtextwriter failed to run successfully.
Hint: You can goto /root/HiBench-master/report/wordcount/prepare/conf/../bench.log to check for detailed log.
Opening log tail for you:

> at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.hadoop.net.SocketIOWithTimeout.connect(SocketIOWithTimeout.java:206)
	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:530)
	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:494)
	at org.apache.hadoop.ipc.Client$Connection.setupConnection(Client.java:614)
	at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:713)
	at org.apache.hadoop.ipc.Client$Connection.access$2900(Client.java:375)
	at org.apache.hadoop.ipc.Client.getConnection(Client.java:1524)
	at org.apache.hadoop.ipc.Client.call(Client.java:1447)
	... 43 more

**Comment by akaito1412** [comment]
I already set the hibench.hadoop.configure.dir. 
but this another error message 

> [root@master1 HiBench-master]# workloads/wordcount/prepare/prepare.sh 
patching args=
Parsing conf: /root/HiBench-master/conf/00-default-properties.conf
Parsing conf: /root/HiBench-master/conf/01-default-streamingbench.conf
Parsing conf: /root/HiBench-master/conf/10-data-scale-profile.conf
Parsing conf: /root/HiBench-master/conf/20-samza-common.conf
Parsing conf: /root/HiBench-master/conf/30-samza-workloads.conf
Parsing conf: /root/HiBench-master/conf/99-user_defined_properties.conf
Parsing conf: /root/HiBench-master/workloads/wordcount/conf/00-wordcount-default.conf
Parsing conf: /root/HiBench-master/workloads/wordcount/conf/10-wordcount-userdefine.conf
Probing spark verison, may last long at first time...
probe sleep jar: /usr/lib/hadoop-mapreduce//hadoop-mapreduce-client-jobclient-tests.jar
start HadoopPrepareWordcount bench
hdfs rm -r: /usr/bin/hadoop --config /etc/hadoop/conf/ fs -rm -r -skipTrash hdfs://10.5.1.160:50070/HiBench/Wordcount/Input
rm: Call From master1/10.5.1.160 to master1:50070 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused

> Submit MapReduce Job: /usr/bin/hadoop --config /etc/hadoop/conf/ jar /usr/lib/hadoop-mapreduce/hadoop-mapreduce-examples-2.6.0-cdh5.8.0.jar randomtextwriter -D mapreduce.randomtextwriter.totalbytes=3200000000 -D mapreduce.job.maps=12 -D mapreduce.job.reduces=6 -D mapreduce.output.fileoutputformat.compress=false hdfs://10.5.1.160:50070/HiBench/Wordcount/Input
16/09/14 14:45:21 WARN security.UserGroupInformation: PriviledgedActionException as:root (auth:SIMPLE) cause:java.net.ConnectException: Call From master1/10.5.1.160 to master1:50070 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
java.net.ConnectException: Call From master1/10.5.1.160 to master1:50070 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
Caused by: java.net.ConnectException: Connection refused
        ... 43 more
ERROR: Hadoop job /usr/lib/hadoop-mapreduce/hadoop-mapreduce-examples-2.6.0-cdh5.8.0.jar randomtextwriter failed to run successfully.
Hint: You can goto /root/HiBench-master/report/wordcount/prepare/conf/../bench.log to check for detailed log.
Opening log tail for you:

> at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.hadoop.net.SocketIOWithTimeout.connect(SocketIOWithTimeout.java:206)
	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:530)
	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:494)
	at org.apache.hadoop.ipc.Client$Connection.setupConnection(Client.java:614)
	at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:713)
	at org.apache.hadoop.ipc.Client$Connection.access$2900(Client.java:375)
	at org.apache.hadoop.ipc.Client.getConnection(Client.java:1524)
	at org.apache.hadoop.ipc.Client.call(Client.java:1447)
	... 43 more

**Comment by zhangkang1201** [comment]
Exception in thread "main" java.lang.IllegalAccessError: class org.apache.hadoop.hdfs.web.HftpFileSystem cannot access its superinterface org.apache.hadoop.hdfs.web.TokenAspect$TokenManagementDelegator
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:370)
        at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
        at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
        at org.apache.hadoop.fs.FileSystem.loadFileSystems(FileSystem.java:3268)
        at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:3313)
        at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3352)
        at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:124)
        at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3403)
        at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3371)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:477)
        at org.apache.hadoop.fs.Path.getFileSystem(Path.java:361)
        at HiBench.Utils.checkHdfsPath(Utils.java:52)
        at HiBench.HiveData.init(HiveData.java:634)
        at HiBench.HiveData.generate(HiveData.java:616)
        at HiBench.DataGen.run(DataGen.java:19)
        at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:76)
        at HiBench.DataGen.main(DataGen.java:45)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.hadoop.util.RunJar.run(RunJar.java:318)
        at org.apache.hadoop.util.RunJar.main(RunJar.java:232)
