### ISSUE TITLE
missing config files cause run-all.sh to fail

### ISSUE THREAD

**Issue by harschware** [intel-hadoop/HiBench#363]
Running with commit 1e32312e58a48 in master.   I set spark.conf and hadoop.conf appropriately and find that hibench.masters.hostnames property is missing on first job attempt. On first try I set an empty value for that config in hadoop.conf, which led to some other config missing.  I then noticed that if I copy the 00-default-properties.conf from the 5.0 branch into the conf dir that the the run will continue but that it will fail for other reasons.

Is there some missing config file still?  

```
[builder@plato-nid00030 bin]$ ./run-all.sh 
Prepare micro.sleep ...
Exec script: /home/users/builder/cactus-test-framework/cactus-test-framework/workspace/plato-cactus-hibench_AQA-1256/hibench/bin/workloads/micro/sleep/prepare/prepare.sh
patching args=
Parsing conf: /home/users/builder/cactus-test-framework/cactus-test-framework/workspace/plato-cactus-hibench_AQA-1256/hibench/conf/hadoop.conf
Parsing conf: /home/users/builder/cactus-test-framework/cactus-test-framework/workspace/plato-cactus-hibench_AQA-1256/hibench/conf/hibench.conf
Parsing conf: /home/users/builder/cactus-test-framework/cactus-test-framework/workspace/plato-cactus-hibench_AQA-1256/hibench/conf/spark.conf
Parsing conf: /home/users/builder/cactus-test-framework/cactus-test-framework/workspace/plato-cactus-hibench_AQA-1256/hibench/conf/workloads/micro/sleep.conf
probe sleep jar: /usr/hdp/current/hadoop-mapreduce-client/hadoop-mapreduce-client-jobclient.jar
Traceback (most recent call last):
  File "/home/users/builder/cactus-test-framework/cactus-test-framework/workspace/plato-cactus-hibench_AQA-1256/hibench/bin/functions/load_config.py", line 723, in <module>
    load_config(conf_root, workload_configFile, workload_folder, patching_config)
  File "/home/users/builder/cactus-test-framework/cactus-test-framework/workspace/plato-cactus-hibench_AQA-1256/hibench/bin/functions/load_config.py", line 208, in load_config
    generate_optional_value()
  File "/home/users/builder/cactus-test-framework/cactus-test-framework/workspace/plato-cactus-hibench_AQA-1256/hibench/bin/functions/load_config.py", line 646, in generate_optional_value
    probe_masters_slaves_hostnames()
  File "/home/users/builder/cactus-test-framework/cactus-test-framework/workspace/plato-cactus-hibench_AQA-1256/hibench/bin/functions/load_config.py", line 581, in probe_masters_slaves_hostnames
    HibenchConf['hibench.masters.hostnames'].split() +
KeyError: 'hibench.masters.hostnames'
/home/users/builder/cactus-test-framework/cactus-test-framework/workspace/plato-cactus-hibench_AQA-1256/hibench/bin/functions/workload-functions.sh: line 38: .: filename argument required
.: usage: . filename [arguments]
start PrepareSleep bench
Prepare sleep: nothing to do
finish PrepareSleep bench
Run micro/sleep/hadoop
Exec script: /home/users/builder/cactus-test-framework/cactus-test-framework/workspace/plato-cactus-hibench_AQA-1256/hibench/bin/workloads/micro/sleep/hadoop/run.sh
patching args=
Parsing conf: /home/users/builder/cactus-test-framework/cactus-test-framework/workspace/plato-cactus-hibench_AQA-1256/hibench/conf/hadoop.conf
Parsing conf: /home/users/builder/cactus-test-framework/cactus-test-framework/workspace/plato-cactus-hibench_AQA-1256/hibench/conf/hibench.conf
Parsing conf: /home/users/builder/cactus-test-framework/cactus-test-framework/workspace/plato-cactus-hibench_AQA-1256/hibench/conf/spark.conf
Parsing conf: /home/users/builder/cactus-test-framework/cactus-test-framework/workspace/plato-cactus-hibench_AQA-1256/hibench/conf/workloads/micro/sleep.conf
probe sleep jar: /usr/hdp/current/hadoop-mapreduce-client/hadoop-mapreduce-client-jobclient.jar
Traceback (most recent call last):
  File "/home/users/builder/cactus-test-framework/cactus-test-framework/workspace/plato-cactus-hibench_AQA-1256/hibench/bin/functions/load_config.py", line 723, in <module>
    load_config(conf_root, workload_configFile, workload_folder, patching_config)
  File "/home/users/builder/cactus-test-framework/cactus-test-framework/workspace/plato-cactus-hibench_AQA-1256/hibench/bin/functions/load_config.py", line 208, in load_config
    generate_optional_value()
  File "/home/users/builder/cactus-test-framework/cactus-test-framework/workspace/plato-cactus-hibench_AQA-1256/hibench/bin/functions/load_config.py", line 646, in generate_optional_value
    probe_masters_slaves_hostnames()
  File "/home/users/builder/cactus-test-framework/cactus-test-framework/workspace/plato-cactus-hibench_AQA-1256/hibench/bin/functions/load_config.py", line 581, in probe_masters_slaves_hostnames
    HibenchConf['hibench.masters.hostnames'].split() +
KeyError: 'hibench.masters.hostnames'
/home/users/builder/cactus-test-framework/cactus-test-framework/workspace/plato-cactus-hibench_AQA-1256/hibench/bin/functions/workload-functions.sh: line 38: .: filename argument required
.: usage: . filename [arguments]
start HadoopSleep bench
/home/users/builder/cactus-test-framework/cactus-test-framework/workspace/plato-cactus-hibench_AQA-1256/hibench/bin/workloads/micro/sleep/hadoop/run.sh: line 27: HADOOP_SLEEP_JAR: unbound variable
ERROR: micro/sleep/hadoop failed to run successfully.
```

**Comment by carsonwang** [comment]
To workload the issue, please add the below two lines in hibench.conf. Please let me know if this bypass the error. We can add these to hibench.conf by default.
```
hibench.masters.hostnames
hibench.slaves.hostnames
```

But the problem itself is that it failed to probe the master hostname. What is the value `hibench.spark.master` set in spark.conf? If it is Spark standalone mode, is the Spark UI accessible? Does the UI need to be accessed through a proxy? If it is set to yarn-client, can you also show your hadoop.conf?

**Comment by harschware** [comment]
Hi @carsonwang,  thank you. Yes, those were the only two missing configs.  I had been running into issues with include the 00-default-properties.conf in my conf directory, but once I stopped doing that and created a  new .conf file with only those two properties I am able to run hibench all the way through to graph/nweight errors ( #369 ).  

Here is my hadoop.conf
```
# Hadoop home
hibench.hadoop.home     /usr/hdp/current/hadoop-client

# The path of hadoop executable
hibench.hadoop.executable     ${hibench.hadoop.home}/bin/hadoop

# Hadoop configraution directory
hibench.hadoop.configure.dir  ${hibench.hadoop.home}/etc/hadoop

# The root HDFS path to store HiBench data
hibench.hdfs.master       hdfs://192.168.0.1:8020/user/$USER


# Hadoop release provider. Supported value: apache, cdh5, hdp
hibench.hadoop.release    apache

#Hadoop version. Only hadoop2 is supported
#TODO: remove this
hibench.hadoop.version    hadoop2

hibench.hadoop.examples.jar /usr/hdp/current/hadoop-mapreduce-client/hadoop-mapreduce-examples.jar
hibench.hadoop.examples.test.jar /usr/hdp/current/hadoop-mapreduce-client/hadoop-mapreduce-client-jobclient.jar
```

**Comment by carsonwang** [comment]
You are running on mesos? This is the reason why the script fails to probe the master and slave host names. Currently it only tries Spark Web UI (standalone mode) or `yarn node -list` command to get the slave hosts. We may better support mesos later. For now, I'll add the two configs to hibench.conf by default so you will be able to run the workloads.

However, the monitor.html will not be generated because HiBench doesn't know the slaves. The `throughput/node` in hibench.report will be incorrect as the value is not divided by the node number. If you need these, you can configure the host names manually, i.e.

```
hibench.masters.hostnames  'HOST1'
hibench.slaves.hostnames   'HOST1 HOST2 HOST3'
```

**Comment by harschware** [comment]
@carsonwang   Do the hostnames need to be those that are used to execute a current task?  I'm confused: if I set the hostnames statically like that I'm not sure that would be correct when attempting to calculate throughputs.

If you do it by "yarn node -list" I think you will be getting number of running containers, which of course assumes the task is the only active task in yarn.

**Comment by carsonwang** [comment]
No. "Yarn node -list" returns the nodes running the node manager.  We calculate the throughput by the node number so you can safely set the hostnames statically.
The hostnames are only used to collect system metrics (by ssh to the nodes) and calculate the throughput per node. You can still run the workloads without setting the hostnames correctly.

**Comment by vijaynirm** [comment]
Do we need to set the Slave nodes even for CDH, inorder to get the throughput for each node?
