### ISSUE TITLE
dfsioe prepare fails, unable to find test.build.data property

### ISSUE THREAD

**Issue by harschware** [intel-hadoop/HiBench#380]
On my system I see the following errors when running the dfsioe job.  I go into the prepare directory and run:

```[builder@plato-nid00030 hibench]$ cd bin/workloads/micro/dfsioe/prepare
[builder@plato-nid00030 prepare]$ pwd
/home/users/builder/cactus-test-framework/cactus-test-framework/workspace/plato-cactus-hibench_AQA-1256/hibench/bin/workloads/micro/dfsioe/prepare
[builder@plato-nid00030 prepare]$ cat ../../../../../report/micro/dfsioe/prepare/bench.log 
patching args=
Parsing conf: /home/users/builder/cactus-test-framework/cactus-test-framework/workspace/plato-cactus-hibench_AQA-1256/hibench/conf/hadoop.conf
Parsing conf: /home/users/builder/cactus-test-framework/cactus-test-framework/workspace/plato-cactus-hibench_AQA-1256/hibench/conf/hibench.conf
Parsing conf: /home/users/builder/cactus-test-framework/cactus-test-framework/workspace/plato-cactus-hibench_AQA-1256/hibench/conf/spark.conf
Parsing conf: /home/users/builder/cactus-test-framework/cactus-test-framework/workspace/plato-cactus-hibench_AQA-1256/hibench/conf/workloads/micro/dfsioe.conf
probe sleep jar: /usr/hdp/current/hadoop-mapreduce-client/hadoop-mapreduce-client-jobclient.jar
start HadoopPrepareDFSIOE bench
hdfs rm -r: /usr/hdp/current/hadoop-client/bin/hadoop --config /usr/hdp/current/hadoop-client/etc/hadoop fs -rm -r -skipTrash hdfs://192.168.0.1:8020/user/builder/HiBench/Dfsioe/Input
Deleted hdfs://192.168.0.1:8020/user/builder/HiBench/Dfsioe/Input
Submit MapReduce Job: /usr/hdp/current/hadoop-client/bin/hadoop --config /usr/hdp/current/hadoop-client/etc/hadoop jar /home/users/builder/cactus-test-framework/cactus-test-framework/workspace/plato-cactus-hibench_AQA-1256/hibench/autogen/target/autogen-6.0-SNAPSHOT-jar-with-dependencies.jar org.apache.hadoop.fs.dfsioe.TestDFSIOEnh -Dmapreduce.map.java.opts="-Dtest.build.data=hdfs://192.168.0.1:8020/user/builder/HiBench/Dfsioe/Input -Xmx8192m" -Dmapreduce.reduce.java.opts="-Dtest.build.data=hdfs://192.168.0.1:8020/user/builder/HiBench/Dfsioe/Input -Xmx8192m" -Dtest.build.data=hdfs://192.168.0.1:8020/user/builder/HiBench/Dfsioe/Input -write -skipAnalyze -nrFiles 16 -fileSize 1 -bufferSize 4096
WARNING: Use "yarn jar" to launch YARN applications.
TestFDSIO.0.0.4 Enhanced Version
16/11/15 13:01:47 INFO dfsioe.TestDFSIOEnh: nrFiles = 16
16/11/15 13:01:47 INFO dfsioe.TestDFSIOEnh: fileSize (MB) = 1
16/11/15 13:01:47 INFO dfsioe.TestDFSIOEnh: bufferSize = 4096
16/11/15 13:01:47 INFO client.RMProxy: Connecting to ResourceManager at /192.168.0.33:8050
16/11/15 13:01:48 INFO Configuration.deprecation: mapred.tasktracker.reduce.tasks.maximum is deprecated. Instead, use mapreduce.tasktracker.reduce.tasks.maximum
16/11/15 13:01:48 INFO Configuration.deprecation: mapred.tasktracker.map.tasks.maximum is deprecated. Instead, use mapreduce.tasktracker.map.tasks.maximum
16/11/15 13:01:48 INFO dfsioe.TestDFSIOEnh: maximum concurrent maps = 16
16/11/15 13:01:48 INFO dfsioe.TestDFSIOEnh: creating control file: 1 mega bytes, 16 files
java.lang.RuntimeException: Property test.build.data cannot be empty
	at org.apache.hadoop.fs.dfsioe.DfsioeConfig.safeGet(DfsioeConfig.java:137)
	at org.apache.hadoop.fs.dfsioe.DfsioeConfig.getTestRootDir(DfsioeConfig.java:45)
	at org.apache.hadoop.fs.dfsioe.DfsioeConfig.getControlDir(DfsioeConfig.java:62)
	at org.apache.hadoop.fs.dfsioe.TestDFSIOEnh.createControlFile(TestDFSIOEnh.java:640)
	at org.apache.hadoop.fs.dfsioe.TestDFSIOEnh.run(TestDFSIOEnh.java:602)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:76)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:90)
	at org.apache.hadoop.fs.dfsioe.TestDFSIOEnh.main(TestDFSIOEnh.java:628)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:221)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:136)
ERROR: Hadoop job /home/users/builder/cactus-test-framework/cactus-test-framework/workspace/plato-cactus-hibench_AQA-1256/hibench/autogen/target/autogen-6.0-SNAPSHOT-jar-with-dependencies.jar org.apache.hadoop.fs.dfsioe.TestDFSIOEnh failed to run successfully.
Hint: You can goto /home/users/builder/cactus-test-framework/cactus-test-framework/workspace/plato-cactus-hibench_AQA-1256/hibench/report/dfsioe/prepare/conf/../bench.log to check for detailed log.
Opening log tail for you:

tail: cannot open ‘/home/users/builder/cactus-test-framework/cactus-test-framework/workspace/plato-cactus-hibench_AQA-1256/hibench/report/dfsioe/prepare/conf/../bench.log’ for reading: No such file or directory
```

Now notice that I can run the map reduce job command from the command line and there will be no error
```[builder@plato-nid00030 prepare]$ /usr/hdp/current/hadoop-client/bin/hadoop --config /usr/hdp/current/hadoop-client/etc/hadoop jar /home/users/builder/cactus-test-framework/cactu
s-test-framework/workspace/plato-cactus-hibench_AQA-1256/hibench/autogen/target/autogen-6.0-SNAPSHOT-jar-with-dependencies.jar org.apache.hadoop.fs.dfsioe.TestDFSIOEnh -Dmapreduce.map.java.opts="-Dtest.build.data=hdfs://192.168.0.1:8020/user/builder/HiBench/Dfsioe/Input -Xmx8192m" -Dmapreduce.reduce.java.opts="-Dtest.build.data=hdfs://192.168.0.1:8020/user/builder/HiBench/Dfsioe/Input -Xmx8192m" -Dtest.build.data=hdfs://192.168.0.1:8020/user/builder/HiBench/Dfsioe/Input -write -skipAnalyze -nrFiles 16 -fileSize 1 -bufferSize 4096
WARNING: Use "yarn jar" to launch YARN applications.
TestFDSIO.0.0.4 Enhanced Version
16/11/15 14:29:54 INFO dfsioe.TestDFSIOEnh: nrFiles = 16
16/11/15 14:29:54 INFO dfsioe.TestDFSIOEnh: fileSize (MB) = 1
16/11/15 14:29:54 INFO dfsioe.TestDFSIOEnh: bufferSize = 4096
16/11/15 14:29:54 INFO client.RMProxy: Connecting to ResourceManager at /192.168.0.33:8050
16/11/15 14:29:54 INFO Configuration.deprecation: mapred.tasktracker.reduce.tasks.maximum is deprecated. Instead, use mapreduce.tasktracker.reduce.tasks.maximum
16/11/15 14:29:54 INFO Configuration.deprecation: mapred.tasktracker.map.tasks.maximum is deprecated. Instead, use mapreduce.tasktracker.map.tasks.maximum
16/11/15 14:29:54 INFO dfsioe.TestDFSIOEnh: maximum concurrent maps = 16
16/11/15 14:29:54 INFO dfsioe.TestDFSIOEnh: creating control file: 1 mega bytes, 16 files
16/11/15 14:29:54 INFO dfsioe.DfsioeConfig: Found 'test.build.data' in Hadoop configuration, value is 'hdfs://192.168.0.1:8020/user/builder/HiBench/Dfsioe/Input'
16/11/15 14:29:54 INFO dfsioe.DfsioeConfig: Setting testRootDir to 'hdfs://192.168.0.1:8020/user/builder/HiBench/Dfsioe/Input'
16/11/15 14:29:55 INFO dfsioe.TestDFSIOEnh: created control files for: 16 files
16/11/15 14:29:55 INFO client.RMProxy: Connecting to ResourceManager at /192.168.0.33:8050
16/11/15 14:29:55 INFO client.RMProxy: Connecting to ResourceManager at /192.168.0.33:8050
16/11/15 14:29:55 INFO mapred.FileInputFormat: Total input paths to process : 16
16/11/15 14:29:56 INFO mapreduce.JobSubmitter: number of splits:16
16/11/15 14:29:56 INFO mapreduce.JobSubmitter: Submitting tokens for job: job_1479233973032_0071
16/11/15 14:29:56 INFO impl.YarnClientImpl: Submitted application application_1479233973032_0071
16/11/15 14:29:56 INFO mapreduce.Job: The url to track the job: http://nid00032.local:8088/proxy/application_1479233973032_0071/
16/11/15 14:29:56 INFO mapreduce.Job: Running job: job_1479233973032_0071
16/11/15 14:30:02 INFO mapreduce.Job: Job job_1479233973032_0071 running in uber mode : false
16/11/15 14:30:02 INFO mapreduce.Job:  map 0% reduce 0%
16/11/15 14:30:07 INFO mapreduce.Job:  map 13% reduce 0%
16/11/15 14:30:08 INFO mapreduce.Job:  map 63% reduce 0%
16/11/15 14:30:09 INFO mapreduce.Job:  map 94% reduce 0%
16/11/15 14:30:10 INFO mapreduce.Job:  map 100% reduce 0%
16/11/15 14:30:12 INFO mapreduce.Job:  map 100% reduce 100%
16/11/15 14:30:12 INFO mapreduce.Job: Job job_1479233973032_0071 completed successfully
16/11/15 14:30:12 INFO mapreduce.Job: Counters: 50
	File System Counters
		FILE: Number of bytes read=92871
		FILE: Number of bytes written=2355544
		FILE: Number of read operations=0
		FILE: Number of large read operations=0
		FILE: Number of write operations=0
		HDFS: Number of bytes read=4012
		HDFS: Number of bytes written=16868110
		HDFS: Number of read operations=67
		HDFS: Number of large read operations=0
		HDFS: Number of write operations=18
	Job Counters 
		Launched map tasks=16
		Launched reduce tasks=1
		Data-local map tasks=9
		Rack-local map tasks=7
		Total time spent by all maps in occupied slots (ms)=58427
		Total time spent by all reduces in occupied slots (ms)=3300
		Total time spent by all map tasks (ms)=58427
		Total time spent by all reduce tasks (ms)=3300
		Total vcore-seconds taken by all map tasks=58427
		Total vcore-seconds taken by all reduce tasks=3300
		Total megabyte-seconds taken by all map tasks=598292480
		Total megabyte-seconds taken by all reduce tasks=33792000
	Map-Reduce Framework
		Map input records=16
		Map output records=224
		Map output bytes=92241
		Map output materialized bytes=92961
		Input split bytes=2214
		Combine input records=0
		Combine output records=0
		Reduce input groups=134
		Reduce shuffle bytes=92961
		Reduce input records=224
		Reduce output records=134
		Spilled Records=448
		Shuffled Maps =16
		Failed Shuffles=0
		Merged Map outputs=16
		GC time elapsed (ms)=727
		CPU time spent (ms)=29130
		Physical memory (bytes) snapshot=35356815360
		Virtual memory (bytes) snapshot=185053573120
		Total committed heap usage (bytes)=40205549568
	Shuffle Errors
		BAD_ID=0
		CONNECTION=0
		IO_ERROR=0
		WRONG_LENGTH=0
		WRONG_MAP=0
		WRONG_REDUCE=0
	File Input Format Counters 
		Bytes Read=1798
	File Output Format Counters 
		Bytes Written=90894
```

So it seems to me the command shown in the log, is probably not the same as the command as hibench is in fact executing and this should be investigated.

**Comment by carsonwang** [comment]
Does this occur consistently? Can we get more details in map reduce log?

**Comment by sylv704** [comment]
Hello,
I have this error with HiBench 6.0 consistenly when I execute bin/workloads/micro/dfsioe/prepare/prepare.sh in backround with at. On the contrary when I execute the cript myself "interactively" from the command line it succeeds. I don't know why yet.

**Comment by ZuluPro** [comment]
Is there any fix ?

**Comment by vincent-wangzy** [comment]
Replaced $CMD by eval $CMD does not work in my environment, the same issue still occur

**Comment by xianliangz** [comment]
Replaced $CMD by eval $CMD works for me! Thank you!
