### ISSUE TITLE
Issue while Running Scan module within SQL workload of HiBench 6.0 Project 

### ISSUE THREAD

**Issue by Gopinath05061987** [intel-hadoop/HiBench#414]
Issue while Running Scan module within SQL workload of HiBench 6.0 Project.The project is being run on CDH 5.8 and parcel mode of deployment is used to install the same.

From the Cloudera Manager UI below YARN Configuration is set. The "mapreduce.framework.name" property is set to YARN mode and not to "Local" mode. The same property is set to yarn in mapred-site.xml on the environment. But still when the Scan module of SQL workload is run below error message is seen. Even though the mode is yarn still the local jobs are run. Tried restarting things on Cloudera Manager and even redeployed the HiBench 6.0 project but they don't seem to help. I don't any issue with hadoop and hibench configurations as with the same configuration able to run the above workload on my local VM setup which is also having CDH 5.9 installed though here it is not parcel mode of deployment but RPM based installation.

What could be likely cause of it . Any help would be appreciated on this.  

Application Framework                  Gateway Default Group
mapreduce.framework.name          yarn

Error Message:

java.io.FileNotFoundException: file:/tmp/hadoop-root/mapred/local/1485238423307/user_agents (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at java.io.FileReader.<init>(FileReader.java:58)
        at HiBench.Visit.<init>(Visit.java:47)
        at HiBench.HiveData$DummyToAccessNoMapper.configure(HiveData.java:389)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:106)
        at org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:75)
        at org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:133)
        at org.apache.hadoop.mapred.lib.DelegatingMapper.map(DelegatingMapper.java:53)
        at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:54)
        at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:453)
        at org.apache.hadoop.mapred.MapTask.run(MapTask.java:343)
        at org.apache.hadoop.mapred.LocalJobRunner$Job$MapTaskRunnable.run(LocalJobRunner.java:270)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
2017-01-24 11:43:46,783 INFO  [Thread-43] mapred.LocalJobRunner (LocalJobRunner.java:runTasks(483)) - map task executor complete.
2017-01-24 11:43:47,383 INFO  [main] mapreduce.Job (Job.java:monitorAndPrintJob(1384)) -  map 100% reduce 0%
2017-01-24 11:43:50,867 WARN  [Thread-43] mapred.LocalJobRunner (LocalJobRunner.java:run(587)) - job_local1672350987_0002
java.lang.Exception: java.lang.NullPointerException
        at org.apache.hadoop.mapred.LocalJobRunner$Job.runTasks(LocalJobRunner.java:489)
        at org.apache.hadoop.mapred.LocalJobRunner$Job.run(LocalJobRunner.java:549)

**Comment by anirban99** [comment]
@Gopinath05061987 I am facing the same issue. Did you find a way to solve it ?

**Comment by carsonwang** [comment]
Can you show the content of your `conf/hadoop.conf` here?

**Comment by anirban99** [comment]
This is the conf/hadoop.conf

# Hadoop home
hibench.hadoop.home     /usr/lib/hadoop/hduser/hadoop-2.6.5

# The path of hadoop executable
hibench.hadoop.executable     ${hibench.hadoop.home}/bin/hadoop

# Hadoop configraution directory
hibench.hadoop.configure.dir  ${hibench.hadoop.home}/etc/hadoop

# The root HDFS path to store HiBench data
hibench.hdfs.master       hdfs://localhost:9000

hibench.hadoop.version     hadoop2

# Hadoop release provider. Supported value: apache, cdh5, hdp
hibench.hadoop.release    apache

I'm running Hibench in Spark stand-alone mode. So can the SQL test be run in Spark stand-alone mode properly?

**Comment by carsonwang** [comment]
Yes, it can be run in both Yarn and standalone mode.
The problem seems to your `hibench.hdfs.master` configuration. If you have multiple slaves, please set it using the hostname instead of localhost.

**Comment by somideshmukh** [comment]
I have set hostname instead of localhost in hibench.hdfs.master in conf/hadoop.conf still I am getting zero in throughput while running scan in standalone mode . below is my hadoop.conf file

# Hadoop home
hibench.hadoop.home    /root/hadoop-2.7.1

# The path of hadoop executable
hibench.hadoop.executable     ${hibench.hadoop.home}/bin/hadoop

# Hadoop configraution directory
hibench.hadoop.configure.dir  ${hibench.hadoop.home}/etc/hadoop

# The root HDFS path to store HiBench data
hibench.hdfs.master       hdfs://pts00450-vm8:9000 


# Hadoop release provider. Supported value: apache, cdh5, hdp
hibench.hadoop.release    apache

**Comment by Pl4tiNuM** [comment]
Hello, any fix for this issue? I am also trying to run SQL benchmarks over Kubernetes and getting the error above.

The rest of the benchmarks (micro,ml,graph,websearch) work fine.
