### ISSUE TITLE
streaming identity run into ERROR CheckpointWriter: Could not submit checkpoint task to the thread pool executor

### ISSUE THREAD

**Issue by yongjianxu** [intel-hadoop/HiBench#416]
Hello:

I am running hibench.streaming.identity with the following configuration.
Hibench: 6.0.1
kafka: 0.10.1.1
zookeeper: 3.4.9
spark: 2.1.0
apache hadoop: 2.7.3

I run into the following error. I guess it could be caused by thread pool size is small (=1). It might be resolved if it is able to enlarge the  java.util.concurrent.ThreadPoolExecutor pool size.
But I do not know how to change the pool size in the test. can you please provide some help?

yong@uvm:/workspace/hibench/601/HiBench-master$ head -n 20 /workspace/hibench/601/HiBench-master/report/identity/spark/conf/../bench.log
metrics is being written to kafka topic SPARK_identity_1_1_100_1486460144659
Reporter TopicSPARK_identity_1_1_100_1486460144659
17/02/07 17:36:49 ERROR CheckpointWriter: Could not submit checkpoint task to the thread pool executor
java.util.concurrent.RejectedExecutionException: Task org.apache.spark.streaming.CheckpointWriter$CheckpointWriteHandler@8f7743e rejected from java.util.concurrent.ThreadPoolExecutor@37856079[**# _Running, pool size = 1, active threads = 1_**, queued tasks = 1000, completed tasks = 235]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369)
	at org.apache.spark.streaming.CheckpointWriter.write(Checkpoint.scala:284)
	at org.apache.spark.streaming.scheduler.JobGenerator.doCheckpoint(JobGenerator.scala:297)
	at org.apache.spark.streaming.scheduler.JobGenerator.org$apache$spark$streaming$scheduler$JobGenerator$$processEvent(JobGenerator.scala:186)
	at org.apache.spark.streaming.scheduler.JobGenerator$$anon$1.onReceive(JobGenerator.scala:89)
	at org.apache.spark.streaming.scheduler.JobGenerator$$anon$1.onReceive(JobGenerator.scala:88)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
17/02/07 17:36:49 ERROR CheckpointWriter: Could not submit checkpoint task to the thread pool executor
java.util.concurrent.RejectedExecutionException: Task org.apache.spark.streaming.CheckpointWriter$CheckpointWriteHandler@5908fe8d rejected from java.util.concurrent.ThreadPoolExecutor@37856079[Running, pool size = 1, active threads = 1, queued tasks = 1000, completed tasks = 235]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369)
	at org.apache.spark.streaming.CheckpointWriter.write(Checkpoint.scala:284)
	at org.apache.spark.streaming.scheduler.JobGenerator.doCheckpoint(JobGenerator.scala:297)

Thanks 
Best wishes
yong

**Comment by yongjianxu** [comment]
I can get the processed topic data. So I guess it might be caused of small thread pool size.

yong@uvm:/workspace/kafka/bin/2.11-0.10.1.1/kafka_2.11-0.10.1.1$ bin/kafka-console-consumer.sh --bootstrap-server uvm:9092 --topic SPARK_identity_1_1_100_1486460144659 --from-beginning
1486460149165:1486460151891
1486460151168:1486460153097
1486460153164:1486460154006
1486460155165:1486460154743
1486460157168:1486460156254
1486460159164:1486460158233
1486460161164:1486460160227
1486460163164:1486460162243

**Comment by yongjianxu** [comment]
Hello, 

I think I found the cause.
The datanode of my HDFS is running with a HDD which is very slow.
It incured a long processing time for checkpointing.

Fix method:
1. I tried to turn off checkpointing and it worked.
2. I tried to set "conf/spark.conf:hibench.streambench.spark.batchInterval" to a larger value. it worked.

BR
yong

**Comment by rkdani** [comment]
Hi Yong,

I am getting the same problem where spark identity job fails after few minutes with the following error:
Can please help here ? I 've tried to turn off the check-pointing by setting up "hibench.streambench.spark.checkpointPath false" and increase the batch interval to "hibench.streambench.spark.batchInterval          200". 

is anything need to be changed. appreciate help here.

============================
17/04/09 22:49:53 INFO cluster.StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
17/04/09 22:57:53 ERROR streaming.CheckpointWriter: Could not submit checkpoint task to the thread pool executor
java.util.concurrent.RejectedExecutionException: Task org.apache.spark.streaming.CheckpointWriter$CheckpointWriteHandler@5bcc988d rejected from java.util.concurrent.ThreadPoolExecutor@189520d6[Running, pool size = 1, active threads = 1, queued tasks = 1000, completed tasks = 3788]
        at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047)
        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823)
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369)
        at org.apache.spark.streaming.CheckpointWriter.write(Checkpoint.scala:284)
        at org.apache.spark.streaming.scheduler.JobGenerator.doCheckpoint(JobGenerator.scala:297)
        at org.apache.spark.streaming.scheduler.JobGenerator.org$apache$spark$streaming$scheduler$JobGenerator$$processEvent(JobGenerator.scala:186)
        at org.apache.spark.streaming.scheduler.JobGenerator$$anon$1.onReceive(JobGenerator.scala:89)
        at org.apache.spark.streaming.scheduler.JobGenerator$$anon$1.onReceive(JobGenerator.scala:88)
        at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)

**Comment by isabelbongo** [comment]
when I run the bin / workloads / streaming / repartition / spark / run.sh script it shows INFO Closing socket connection to /10.0.5.46. (kafka.network.processor) in the kafka cluster and the following org.apache.spark.SparkException: ArrayBuffer (java.nio.channels.ClosedChannelException) exception in hibench.
please help me I have been struggling with this situation for a month now and so has the Flink cluster. the data is not generated and I can not get any results.

**Comment by isabelbongo** [comment]
java.util.concurrent.RejectedExecutionException: Task org.apache.spark.streaming.CheckpointWriter$CheckpointWriteHandler@1cb76bf1 rejected from java.util.concurrent.ThreadPoolExecutor@1cc65feb[Runnin...
        at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
        at org.apache.spark.streaming.CheckpointWriter.write(Checkpoint.scala:287)
        at org.apache.spark.streaming.scheduler.JobGenerator.doCheckpoint(JobGenerator.scala:297)
        at org.apache.spark.streaming.scheduler.JobGenerator.org$apache$spark$streaming$scheduler$JobGenerator$$processEvent(JobGenerator.scala:186)
        at org.apache.spark.streaming.scheduler.JobGenerator$$anon$1.onReceive(JobGenerator.scala:89)
        at org.apache.spark.streaming.scheduler.JobGenerator$$anon$1.onReceive(JobGenerator.scala:88)
        at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)

**Comment by isabelbongo** [comment]
the hibench log shows the following error:

 ERROR kafka.DirectKafkaInputDStream: ArrayBuffer(java.nio.channels.ClosedChannelException)
19/01/21 12:34:42 ERROR scheduler.JobScheduler: Error generating jobs for time 1548074082000 ms
org.apache.spark.SparkException: ArrayBuffer(java.nio.channels.ClosedChannelException)
        at org.apache.spark.streaming.kafka.DirectKafkaInputDStream.latestLeaderOffsets(DirectKafkaInputDStream.scala:123)
        at org.apache.spark.streaming.kafka.DirectKafkaInputDStream.compute(DirectKafkaInputDStream.scala:145)
        at org.apache.spark.streaming.dstream.DStream$$anonfun$getOrCompute$1$$anonfun$1$$anonfun$apply$7.apply(DStream.scala:342)
        at org.apache.spark.streaming.dstream.DStream$$anonfun$getOrCompute$1$$anonfun$1$$anonfun$apply$7.apply(DStream.scala:342)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
        at org.apache.spark.streaming.dstream.DStream$$anonfun$getOrCompute$1$$anonfun$1.apply(DStream.scala:341)
        at org.apache.spark.streaming.dstream.DStream$$anonfun$getOrCompute$1$$anonfun$1.apply(DStream.scala:341)
        at org.apache.spark.streaming.dstream.DStream.createRDDWithLocalProperties(DStream.scala:416)
        at org.apache.spark.streaming.dstream.DStream$$anonfun$getOrCompute$1.apply(DStream.scala:336)
        at org.apache.spark.streaming.dstream.DStream$$anonfun$getOrCompute$1.apply(DStream.scala:334)
        at scala.Option.orElse(Option.scala:289)
