### ISSUE TITLE
java.lang.IllegalArgumentException: Wrong FS: hdfs://sppcluster:8020/***/io_control, expected: hdfs://sppcluster

### ISSUE THREAD

**Issue by DasiyShang** [intel-hadoop/HiBench#419]
I encountered this error when I run './workloads/dfsioe/prepare/prepare.sh'
17/02/27 21:11:49 INFO dfsioe.DfsioeConfig: Setting testRootDir to 'hdfs://hd151.bd:8020/user/root/HiBench/Dfsioe/Input'
java.lang.IllegalArgumentException: Wrong FS: hdfs://hd151.bd:8020/user/root/HiBench/Dfsioe/Input/io_control, expected: hdfs://sppcluster
	at org.apache.hadoop.fs.FileSystem.checkPath(FileSystem.java:646)
	at org.apache.hadoop.hdfs.DistributedFileSystem.getPathName(DistributedFileSystem.java:194)
	at org.apache.hadoop.hdfs.DistributedFileSystem.access$000(DistributedFileSystem.java:106)
	at org.apache.hadoop.hdfs.DistributedFileSystem$14.doCall(DistributedFileSystem.java:717)
	at org.apache.hadoop.hdfs.DistributedFileSystem$14.doCall(DistributedFileSystem.java:713)
	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
	at org.apache.hadoop.hdfs.DistributedFileSystem.delete(DistributedFileSystem.java:713)
	at org.apache.hadoop.fs.dfsioe.TestDFSIOEnh.createControlFile(TestDFSIOEnh.java:640)
	at org.apache.hadoop.fs.dfsioe.TestDFSIOEnh.run(TestDFSIOEnh.java:602)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:76)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:90)
	at org.apache.hadoop.fs.dfsioe.TestDFSIOEnh.main(TestDFSIOEnh.java:628)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:221)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:136)

**Comment by DasiyShang** [comment]
The hibench.hdfs.master should not be added port when the cluster is HA.
