### ISSUE TITLE
HiBench spark run.sh issue

### ISSUE THREAD

**Issue by kkuser** [intel-hadoop/HiBench#420]
Hello~
I have successfully run hadoop benchmark, which works well. Also, prepare.sh is good on spark. However, I cannot run spark/run.sh:

```
[yyl@spark-client-2259378-1-10217835 HiBench]$ bin/workloads/micro/wordcount/spark/run.sh
patching args=
Parsing conf: /home/yliu28/HiBench/conf/hadoop.conf
Parsing conf: /home/yliu28/HiBench/conf/hibench.conf
Parsing conf: /home/yliu28/HiBench/conf/spark.conf
Parsing conf: /home/yliu28/HiBench/conf/workloads/micro/wordcount.conf
probe sleep jar: /opt/hadoop/share/hadoop/mapreduce/hadoop-mapreduce-client-jobclient-2.7.3-tests.jar
spark://10.224.30.157:7077 10.224.30.157
start ScalaSparkWordcount bench
hdfs rm -r: /opt/hadoop/bin/hadoop --config /opt/hadoop/etc/hadoop fs -rm -r -skipTrash swift://test-swifta-hibench.strati-cdc-demo2/HiBench/Wordcount/Output
rm: `swift://test-swifta-hibench.strati-cdc-demo2/HiBench/Wordcount/Output': No such file or directory
hdfs du -s: /opt/hadoop/bin/hadoop --config /opt/hadoop/etc/hadoop fs -du -s swift://test-swifta-hibench.strati-cdc-demo2/HiBench/Wordcount/Input
Export env: SPARKBENCH_PROPERTIES_FILES=/home/yliu28/HiBench/report/wordcount/spark/conf/sparkbench/sparkbench.conf
Submit Spark job: /opt/spark/bin/spark-submit  --properties-file /home/yliu28/HiBench/report/wordcount/spark/conf/sparkbench/spark.conf --class com.intel.hibench.sparkbench.micro.ScalaWordCount --master spark://10.224.30.157:7077  /home/yliu28/HiBench/sparkbench/assembly/target/sparkbench-assembly-6.0-SNAPSHOT-dist.jar swift://test-swifta-hibench.strati-cdc-demo2/HiBench/Wordcount/Input swift://test-swifta-hibench.strati-cdc-demo2/HiBench/Wordcount/Output
java.lang.NoSuchMethodError: scala.reflect.api.JavaUniverse.runtimeMirror(Ljava/lang/ClassLoader;)Lscala/reflect/api/JavaMirrors$JavaMirror;
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
ERROR: Spark job com.intel.hibench.sparkbench.micro.ScalaWordCount failed to run successfully.
Hint: You can goto /home/yliu28/HiBench/report/wordcount/spark/conf/../bench.log to check for detailed log.
Opening log tail for you:

	at com.intel.hibench.sparkbench.micro.ScalaWordCount.main(ScalaWordCount.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:738)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:187)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:212)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:126)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

**Comment by gczsjdy** [comment]
Can you show me the full log?

**Comment by NitzKash** [comment]
Hello, we are facing a similar problem for the same command: `bin/workloads/micro/wordcount/spark/run.sh`

The full contents of the log file:
`java.lang.ClassNotFoundException: com.intel.hibench.sparkbench.micro.ScalaSort
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:270)
	at org.apache.spark.util.Utils$.classForName(Utils.scala:175)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:689)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)`

Please kindly look into the matter. 
We would be very thankful if someone could help us with the issue.

**Comment by carsonwang** [comment]
Usually this means Hibench was not build correctly. Please specify scala and spark version according to your environment. See the document https://github.com/intel-hadoop/HiBench/blob/master/docs/build-hibench.md

**Comment by NitzKash** [comment]
thanks :)
