### ISSUE TITLE
Required field 'nimbus_uptime_secs' was not found (hibench-5.0 storm-0.10.0

### ISSUE THREAD

**Issue by DasiyShang** [intel-hadoop/HiBench#425]
[root@hd152 streamingbench]# ./storm/bin/run.sh
The error message:
org.apache.thrift.protocol.TProtocolException: Required field 'nimbus_uptime_secs' was not found in serialized data! Struct: com.intel.hibench.streambench.storm.thrift.generated.ClusterSummary$ClusterSummaryStandardScheme@1275a539
        at com.intel.hibench.streambench.storm.thrift.generated.ClusterSummary$ClusterSummaryStandardSche...
        at com.intel.hibench.streambench.storm.thrift.generated.ClusterSummary$ClusterSummaryStandardSche...

**Comment by DasiyShang** [comment]
The full log:
Submit Storm Job: /usr/hdp/2.3.4.7-4/storm/bin/storm jar /usr/hdp/2.3.4.7-4/hibench-5.0-branch/src/streambench/stormbench/target/streaming-bench-storm-0.1-SNAPSHOT-jar-with-dependencies.jar com.intel.hibench.streambench.storm.RunBench /usr/hdp/2.3.4.7-4/hibench-5.0-branch/report/streamingbench/storm/conf/sparkbench/sparkbench.conf storm
Benchmark starts... local:false  identity   Frameworks:Storm
Topic:identity consumerGroup:HiBench  zkHost:hd151.bd:2181,hd152.bd:2181,hd153.bd:2181
945  [main] INFO  b.s.u.Utils - Using defaults.yaml from resources
1035 [main] INFO  b.s.u.Utils - Using storm.yaml from resources
1095 [main] INFO  b.s.u.Utils - Using defaults.yaml from resources
1123 [main] INFO  b.s.u.Utils - Using storm.yaml from resources
1141 [main] INFO  b.s.StormSubmitter - Generated ZooKeeper secret payload for MD5-digest: -58167304808724...
1143 [main] INFO  b.s.s.a.AuthUtils - Got AutoCreds []
1158 [main] INFO  b.s.u.StormBoundedExponentialBackoffRetry - The baseSleepTimeMs [2000] the maxSleepTime...
1190 [main] INFO  b.s.u.StormBoundedExponentialBackoffRetry - The baseSleepTimeMs [2000] the maxSleepTime...
1191 [main] INFO  b.s.u.StormBoundedExponentialBackoffRetry - The baseSleepTimeMs [2000] the maxSleepTime...
1199 [main] INFO  b.s.u.StormBoundedExponentialBackoffRetry - The baseSleepTimeMs [2000] the maxSleepTime...
1207 [main] INFO  b.s.u.StormBoundedExponentialBackoffRetry - The baseSleepTimeMs [2000] the maxSleepTime...
1215 [main] INFO  b.s.u.StormBoundedExponentialBackoffRetry - The baseSleepTimeMs [2000] the maxSleepTime...
1229 [main] INFO  b.s.StormSubmitter - Uploading topology jar /usr/hdp/2.3.4.7-4/hibench-5.0-branch/src/s...
2940 [main] INFO  b.s.StormSubmitter - Successfully uploaded topology jar to assigned location: /hadoop/s...
2940 [main] INFO  b.s.StormSubmitter - Submitting topology identity in distributed mode with conf {"storm...
4507 [main] INFO  b.s.StormSubmitter - Finished submitting topology: identity
org.apache.thrift.protocol.TProtocolException: Required field 'nimbus_uptime_secs' was not found in serialized data! Struct: com.intel.hibench.streambench.storm.thrift.generated.ClusterSummary$ClusterSummaryStandardScheme@1275a539
        at com.intel.hibench.streambench.storm.thrift.generated.ClusterSummary$ClusterSummaryStandardSche...
        at com.intel.hibench.streambench.storm.thrift.generated.ClusterSummary$ClusterSummaryStandardSche...
        at com.intel.hibench.streambench.storm.thrift.generated.ClusterSummary.read(ClusterSummary.java:455)
        at com.intel.hibench.streambench.storm.thrift.generated.Nimbus$getClusterInfo_result$getClusterIn...
        at com.intel.hibench.streambench.storm.thrift.generated.Nimbus$getClusterInfo_result$getClusterIn...
        at com.intel.hibench.streambench.storm.thrift.generated.Nimbus$getClusterInfo_result.read(Nimbus....
        at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:78)
        at com.intel.hibench.streambench.storm.thrift.generated.Nimbus$Client.recv_getClusterInfo(Nimbus....
        at com.intel.hibench.streambench.storm.thrift.generated.Nimbus$Client.getClusterInfo(Nimbus.java:...
        at com.intel.hibench.streambench.storm.metrics.StatFacade.getTopologyId(StatFacade.java:67)
        at com.intel.hibench.streambench.storm.metrics.StatFacade.<init>(StatFacade.java:58)
        at com.intel.hibench.streambench.storm.metrics.Reporter.run(Reporter.java:38)
        at java.lang.Thread.run(Thread.java:745)
^CTraceback (most recent call last):
  File "/usr/hdp/2.3.4.7-4/hibench-5.0-branch/bin/functions/execute_with_log.py", line 131, in <module>
    command_lines=sys.argv[2:]))
  File "/usr/hdp/2.3.4.7-4/hibench-5.0-branch/bin/functions/execute_with_log.py", line 82, in execute
    for line in lines_iterator:
KeyboardInterrupt
finish1 StormStreamingBench bench

**Comment by carsonwang** [comment]
Any chance to try HiBench 6.0? Check this https://github.com/intel-hadoop/HiBench/blob/master/docs/run-streamingbench.md
