### ISSUE TITLE
Launching nutchindexing on CDH5

### ISSUE THREAD

**Issue by Jaeki** [intel-hadoop/HiBench#46]
Hi.

I am using CDH5 5.0.2 which is latest.

and I have downloaded latest HiBench source.

All benchmark suites(wordcount, terasort, kmeans, hive bench, etc.) operate pretty well except nutchindexing.

When I ran nutchindexing/bin/prepare.sh. it looks finished preparation job without errors.

After that, if I run nutchindexing/bin/run.sh, I got below error logs

-----------------------------
========== running nutchindex data ==========
JAVA_HOME=/usr/lib/jvm/java-7-oracle-cloudera
HADOOP_HOME=/opt/cloudera/parcels/CDH
HADOOP_EXECUTABLE=/opt/cloudera/parcels/CDH/bin/hadoop
HADOOP_CONF_DIR=/etc/alternatives/hadoop-conf
HADOOP_EXAMPLES_JAR=/opt/cloudera/parcels/CDH/lib/hadoop-mapreduce/hadoop-mapreduce-examples.jar
MAPRED_EXECUTABLE=/opt/cloudera/parcels/CDH/bin/mapred
nutchindexing/bin/run.sh: line 26: check-compress: command not found
Deleted /HiBench/Nutch/Input/indexes
/root/HiBench/bin/../nutchindexing/nutch-1.2-cdh5
JAVA_HOME=/usr/lib/jvm/java-7-oracle-cloudera
HADOOP_HOME=/opt/cloudera/parcels/CDH
HADOOP_EXECUTABLE=/opt/cloudera/parcels/CDH/bin/hadoop
HADOOP_CONF_DIR=/etc/alternatives/hadoop-conf
HADOOP_EXAMPLES_JAR=/opt/cloudera/parcels/CDH/lib/hadoop-mapreduce/hadoop-mapreduce-examples.jar
MAPRED_EXECUTABLE=/opt/cloudera/parcels/CDH/bin/mapred
14/07/01 11:15:22 INFO indexer.Indexer: Indexer: starting at 2014-07-01 11:15:22
14/07/01 11:15:22 INFO indexer.IndexerMapReduce: IndexerMapReduce: crawldb: /HiBench/Nutch/Input/crawldb
14/07/01 11:15:22 INFO indexer.IndexerMapReduce: IndexerMapReduce: linkdb: /HiBench/Nutch/Input/linkdb
14/07/01 11:15:22 INFO indexer.IndexerMapReduce: IndexerMapReduces: adding segment: /HiBench/Nutch/Input/segments/*
14/07/01 11:15:23 INFO client.RMProxy: Connecting to ResourceManager at swat3-33/172.23.33.1:8032
14/07/01 11:15:23 INFO client.RMProxy: Connecting to ResourceManager at swat3-33/172.23.33.1:8032
14/07/01 11:15:24 INFO mapred.FileInputFormat: Total input paths to process : 432
14/07/01 11:15:25 INFO mapreduce.JobSubmitter: number of splits:432
14/07/01 11:15:25 INFO mapreduce.JobSubmitter: Submitting tokens for job: job_1404170587682_0022
14/07/01 11:15:25 INFO impl.YarnClientImpl: Submitted application application_1404170587682_0022
14/07/01 11:15:25 INFO mapreduce.Job: The url to track the job: http://swat3-33:8088/proxy/application_1404170587682_0022/
14/07/01 11:15:25 INFO mapreduce.Job: Running job: job_1404170587682_0022
14/07/01 11:15:32 INFO mapreduce.Job: Job job_1404170587682_0022 running in uber mode : false
14/07/01 11:15:32 INFO mapreduce.Job:  map 0% reduce 0%
14/07/01 11:15:35 INFO mapreduce.Job: Task Id : attempt_1404170587682_0022_m_000000_0, Status : FAILED
Error: java.lang.RuntimeException: Error in configuring object
        at org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:109)
        at org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:75)
        at org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:133)
        at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:426)
        at org.apache.hadoop.mapred.MapTask.run(MapTask.java:342)
        at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:168)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:415)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1548)
        at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:163)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:106)
        ... 9 more
Caused by: java.lang.RuntimeException: Error in configuring object
        at org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:109)
        at org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:75)
        at org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:133)
        at org.apache.hadoop.mapred.MapRunner.configure(MapRunner.java:38)
        ... 14 more
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:106)
        ... 17 more
Caused by: java.lang.NullPointerException
        at org.apache.nutch.plugin.PluginManifestParser.parsePluginFolder(PluginManifestParser.java:87)
        at org.apache.nutch.plugin.PluginRepository.<init>(PluginRepository.java:71)
        at org.apache.nutch.plugin.PluginRepository.get(PluginRepository.java:95)
        at org.apache.nutch.indexer.IndexingFilters.<init>(IndexingFilters.java:60)
        at org.apache.nutch.indexer.IndexerMapReduce.configure(IndexerMapReduce.java:61)
        ... 22 more

^C^C^C

--------------------------------------

Any comments about this error?

Thank you in advance.

**Comment by adrian-wang** [comment]
Let's close this first. If problem persists, you're welcome to reopen this.
Thanks!
