### ISSUE TITLE
Fail to run spark streaming test

### ISSUE THREAD

**Issue by Adamhyw** [intel-hadoop/HiBench#464]
Hi, I am facing an streaming test issue: everytime I ran spark-streaming test, it always shows this error:
Exception in thread "main" java.lang.NoSuchMethodError: scala.runtime.IntRef.create(I)Lscala/runtime/IntRef;
        at kafka.admin.AdminUtils$.assignReplicasToBrokers(AdminUtils.scala:74)
        at kafka.admin.AdminUtils$.createTopic(AdminUtils.scala:171)
        at com.intel.hibench.common.streaming.metrics.MetricsUtil$.createTopic(MetricsUtil.scala:39)
        at com.intel.hibench.sparkbench.streaming.RunBench$.main(RunBench.scala:66)
        at com.intel.hibench.sparkbench.streaming.RunBench.main(RunBench.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:731)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
But I already built HiBench in correct scala version the same as my cluster
Version info:
CDH-5.10.0
Spark-1.6.0
Scala-2.10.5
Kafka-0.8.2.0

Can somebody tell me what is the problem or do I need to modify my configuration for dependency

**Comment by carsonwang** [comment]
Did you specify scala and spark version correctly `-Dspark=1.6 -Dscala=2.10` when build HiBench?
See https://github.com/intel-hadoop/HiBench/blob/master/docs/build-hibench.md
