### ISSUE TITLE
Error running sparkbench streaming => java.lang.NoSuchMethodError: kafka.admin.AdminUtils$.createTopic

### ISSUE THREAD

**Issue by muralipusala** [intel-hadoop/HiBench#473]
I am benchmarking with Hibench on 4 node virtual cluster with Cloudera 5.11.  I started with identity workload using the command 

> "bin/workloads/streaming/identity/spark/run.sh"

I encounter the error massage
kafka.admin.AdminUtils$.createTopic(Lorg/I0Itec/zkclient/ZkClient;Ljava/lang/String;IILjava/util/Properties;)V

but the file "MetricsUtil.scala" actually calling the function createTopic(ZkClient,String,Int,Int). 

List of packages and versions:
HiBench 6.0 release
Scala 2.10.4
spark 1.6.0 (YARN)

Error message: 
17/06/15 18:20:02 INFO zkclient.ZkClient: Waiting for keeper state SyncConnected
17/06/15 18:20:02 INFO zookeeper.ClientCnxn: Opening socket connection to server vm-cluster-node1/10.211.55.100:2181. Will not attempt to authenticate using SASL (unknown error)
17/06/15 18:20:02 INFO zookeeper.ClientCnxn: Socket connection established, initiating session, client: /10.211.55.100:34761, server: vm-cluster-node1/10.211.55.100:2181
17/06/15 18:20:02 INFO zookeeper.ClientCnxn: Session establishment complete on server vm-cluster-node1/10.211.55.100:2181, sessionid = 0x15cacbbd0f3008d, negotiated timeout = 6000
17/06/15 18:20:02 INFO zkclient.ZkClient: zookeeper state changed (SyncConnected)
17/06/15 18:20:02 INFO zkclient.ZkEventThread: Terminate ZkClient event thread.
17/06/15 18:20:02 INFO zookeeper.ClientCnxn: EventThread shut down
17/06/15 18:20:02 INFO zookeeper.ZooKeeper: Session: 0x15cacbbd0f3008d closed
Exception in thread "main" java.lang.NoSuchMethodError: kafka.admin.AdminUtils$.createTopic(Lorg/I0Itec/zkclient/ZkClient;Ljava/lang/String;IILjava/util/Properties;)V
        at com.intel.hibench.common.streaming.metrics.MetricsUtil$.createTopic(MetricsUtil.scala:39)
        at com.intel.hibench.sparkbench.streaming.RunBench$.main(RunBench.scala:66)
        at com.intel.hibench.sparkbench.streaming.RunBench.main(RunBench.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:730)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

**Comment by carsonwang** [comment]
Did you specify `-Dspark=1.6 -Dscala=2.10` when building HiBench? What's your kafka version?

**Comment by muralipusala** [comment]
Yes, I do specified the flags. -Dspark=1.6 -Dscala=2.10.

I am using Kafka_2.10_0.8.2.2.

**Comment by BalaBalaYi** [comment]
Same problems! 
With " -Dspark=2.1"
Using "kafka 01020"

**Comment by BalaBalaYi** [comment]
have you resolve this problem? ty @muralipusala

**Comment by Mr-San** [comment]
直接从源码里注释掉报错的那行，任务继续

**Comment by varuy322** [comment]
> 直接从源码里注释掉报错的那行，任务继续

if you commit it, spark will not create topic ,how it works well?
