### ISSUE TITLE
Error when running spark yarn on cluster 

### ISSUE THREAD

**Issue by BalaBalaYi** [intel-hadoop/HiBench#491]
## Hibench_version: newest(v6.0)

yarn on client is ok, but yarn on cluster meet the following erros:

## hadoop.conf:
hibench.hadoop.home     /opt/cloudera/parcels/CDH-5.12.0-1.cdh5.12.0.p0.29
hibench.hadoop.executable     /bin/hadoop
hibench.hadoop.configure.dir  /etc/hadoop/conf.cloudera.yarn
hibench.hdfs.master       hdfs://hps72.cdh.com:8020
hibench.hadoop.release    cdh5

## spark.conf
hibench.spark.home      /opt/cloudera/parcels/SPARK2/lib/spark2

hibench.spark.master    yarn-cluster

hibench.yarn.executor.num     2
hibench.yarn.executor.cores   4

spark.executor.memory  4g
spark.driver.memory    4g
...

### hibench's console:
[root@hps72 HiBench]# ./bin/workloads/micro/wordcount/spark/run.sh
patching args=
Parsing conf: /opt/HiBench/conf/hadoop.conf
Parsing conf: /opt/HiBench/conf/hibench.conf
Parsing conf: /opt/HiBench/conf/spark.conf
Parsing conf: /opt/HiBench/conf/workloads/micro/wordcount.conf
probe sleep jar: /opt/cloudera/parcels/CDH-5.12.0-1.cdh5.12.0.p0.29/share/hadoop/mapreduce2/hadoop-mapreduce-client-jobclient-2.4.0-tests.jar
start ScalaSparkWordcount bench
hdfs rm -r: /bin/hadoop --config /etc/hadoop/conf.cloudera.yarn fs -rm -r -skipTrash hdfs://hps72.cdh.com:8020/HiBench/Wordcount/Output
rm: `hdfs://hps72.cdh.com:8020/HiBench/Wordcount/Output': No such file or directory
hdfs du -s: /bin/hadoop --config /etc/hadoop/conf.cloudera.yarn fs -du -s hdfs://hps72.cdh.com:8020/HiBench/Wordcount/Input
Export env: SPARKBENCH_PROPERTIES_FILES=/opt/HiBench/report/wordcount/spark/conf/sparkbench/sparkbench.conf
Export env: HADOOP_CONF_DIR=/etc/hadoop/conf.cloudera.yarn
Submit Spark job: /opt/cloudera/parcels/SPARK2/lib/spark2/bin/spark-submit  --properties-file /opt/HiBench/report/wordcount/spark/conf/sparkbench/spark.conf --class com.intel.hibench.sparkbench.micro.ScalaWordCount --master yarn-cluster --num-executors 2 --executor-cores 4 --executor-memory 4g /opt/HiBench/sparkbench/assembly/target/sparkbench-assembly-6.1-SNAPSHOT-dist.jar hdfs://hps72.cdh.com:8020/HiBench/Wordcount/Input hdfs://hps72.cdh.com:8020/HiBench/Wordcount/Output
17/09/19 14:03:55 INFO util.ShutdownHookManager: Deleting directory /tmp/spark-986470a7-6f9f-4963-b2f4-68781623f181
ERROR: Spark job com.intel.hibench.sparkbench.micro.ScalaWordCount failed to run successfully.
Hint: You can goto /opt/HiBench/report/wordcount/spark/conf/../bench.log to check for detailed log.
Opening log tail for you:

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:755)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:119)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
17/09/19 14:03:55 INFO util.ShutdownHookManager: Shutdown hook called
17/09/19 14:03:55 INFO util.ShutdownHookManager: Deleting directory /tmp/spark-986470a7-6f9f-4963-b2f4-68781623f181

### ## hibench's log:
17/09/19 14:03:53 INFO yarn.Client: Application report for application_1505791627900_0008 (state: RUNNING)
17/09/19 14:03:54 INFO yarn.Client: Application report for application_1505791627900_0008 (state: RUNNING)
17/09/19 14:03:55 INFO yarn.Client: Application report for application_1505791627900_0008 (state: FINISHED)
17/09/19 14:03:55 INFO yarn.Client:
	 client token: N/A
	 diagnostics: User class threw exception: java.lang.ExceptionInInitializerError
	 ApplicationMaster host: 10.255.80.75
	 ApplicationMaster RPC port: 0
	 queue: root.users.root
	 start time: 1505801003133
	 final status: FAILED
	 tracking URL: http://hps72.cdh.com:8088/proxy/application_1505791627900_0008/
	 user: root
Exception in thread "main" org.apache.spark.SparkException: Application application_1505791627900_0008 finished with failed status
	at org.apache.spark.deploy.yarn.Client.run(Client.scala:1106)
	at org.apache.spark.deploy.yarn.Client$.main(Client.scala:1152)
	at org.apache.spark.deploy.yarn.Client.main(Client.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:755)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:119)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
17/09/19 14:03:55 INFO util.ShutdownHookManager: Shutdown hook called
17/09/19 14:03:55 INFO util.ShutdownHookManager: Deleting directory /tmp/spark-986470a7-6f9f-4963-b2f4-68781623f181

### application's log:
17/09/19 14:03:54 ERROR yarn.ApplicationMaster: User class threw exception: java.lang.ExceptionInInitializerError
java.lang.ExceptionInInitializerError
	at com.intel.hibench.sparkbench.common.IOCommon$$anonfun$1.apply(IOCommon.scala:37)
	at com.intel.hibench.sparkbench.common.IOCommon$$anonfun$1.apply(IOCommon.scala:37)
	at scala.Option.getOrElse(Option.scala:121)
	at com.intel.hibench.sparkbench.common.IOCommon.load(IOCommon.scala:36)
	at com.intel.hibench.sparkbench.micro.ScalaWordCount$.main(ScalaWordCount.scala:38)
	at com.intel.hibench.sparkbench.micro.ScalaWordCount.main(ScalaWordCount.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:645)
Caused by: java.lang.NullPointerException
	at scala.collection.immutable.StringLike$class.split(StringLike.scala:208)
	at scala.collection.immutable.StringOps.split(StringOps.scala:29)
	at com.intel.hibench.sparkbench.common.IOCommon$.getPropertiesFromFile(IOCommon.scala:90)
	at com.intel.hibench.sparkbench.common.IOCommon$.<init>(IOCommon.scala:86)
	at com.intel.hibench.sparkbench.common.IOCommon$.<clinit>(IOCommon.scala)
	... 11 more
17/09/19 14:03:54 INFO yarn.ApplicationMaster: Final app status: FAILED, exitCode: 15, (reason: User class threw exception: java.lang.ExceptionInInitializerError)
17/09/19 14:03:54 INFO spark.SparkContext: Invoking stop() from shutdown hook
17/09/19 14:03:54 INFO server.AbstractConnector: Stopped Spark@4c25f206{HTTP/1.1,[http/1.1]}{0.0.0.0:0}

**Comment by AxingguChen** [comment]
Spark 2.1.1
Hadoop 2.7.3
scala 2.11.5

I successfully run WordCount.scala by ./bin/workload/micro/wordcount/spark/run.sh

But I got the same problem when I use the script from above.
`/spark-2.1.1-bin-hadoop2.7/bin/spark-submit  --properties-file /benchmark/spark/HiBench-master/report/wordcount/spark/conf/sparkbench/spark.conf --class com.intel.hibench.sparkbench.micro.ScalaWordCount --master yarn-client --num-executors 6 --executor-cores 5 --executor-memory 4g /benchmark/spark/HiBench-master/sparkbench/assembly/target/sparkbench-assembly-6.1-SNAPSHOT-dist.jar /HiBench/Wordcount/Input /HiBench/Wordcount/Output`

Error:
`Exception in thread "main" java.lang.ExceptionInInitializerError
        at com.intel.hibench.sparkbench.common.IOCommon$$anonfun$1.apply(IOCommo        n.scala:37)
        at com.intel.hibench.sparkbench.common.IOCommon$$anonfun$1.apply(IOCommo        n.scala:37)
        at scala.Option.getOrElse(Option.scala:121)
        at com.intel.hibench.sparkbench.common.IOCommon.load(IOCommon.scala:36)
        at com.intel.hibench.sparkbench.micro.ScalaWordCount$.main(ScalaWordCoun        t.scala:38)
        at com.intel.hibench.sparkbench.micro.ScalaWordCount.main(ScalaWordCount        .scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.        java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces        sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSub        mit$$runMain(SparkSubmit.scala:743)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:18        7)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:212)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:126)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.NullPointerException
        at scala.collection.immutable.StringLike$class.split(StringLike.scala:20        8)
        at scala.collection.immutable.StringOps.split(StringOps.scala:29)
        at com.intel.hibench.sparkbench.common.IOCommon$.getPropertiesFromFile(I        OCommon.scala:90)
        at com.intel.hibench.sparkbench.common.IOCommon$.<init>(IOCommon.scala:8        6)
        at com.intel.hibench.sparkbench.common.IOCommon$.<clinit>(IOCommon.scala        )
        ... 15 more
`
Does it need env supports for the script?

**Comment by vijayarajbala** [comment]
Hello, Ever you find the rootcause for this issue?

**Comment by tobegit3hub** [comment]
I got the similar issue and it only work for yarn-client mode.

```
2019-03-21 22:39:27 INFO  SparkContext:54 - Created broadcast 0 from newAPIHadoopFile at ScalaTeraSort.scala:49
2019-03-21 22:39:27 ERROR ApplicationMaster:91 - User class threw exception: java.lang.ExceptionInInitializerError
java.lang.ExceptionInInitializerError
	at com.intel.hibench.sparkbench.micro.ScalaTeraSort$.main(ScalaTeraSort.scala:53)
	at com.intel.hibench.sparkbench.micro.ScalaTeraSort.main(ScalaTeraSort.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$4.run(ApplicationMaster.scala:706)
Caused by: java.lang.NullPointerException
	at scala.collection.immutable.StringLike$class.split(StringLike.scala:208)
	at scala.collection.immutable.StringOps.split(StringOps.scala:29)
	at com.intel.hibench.sparkbench.common.IOCommon$.getPropertiesFromFile(IOCommon.scala:90)
	at com.intel.hibench.sparkbench.common.IOCommon$.<init>(IOCommon.scala:86)
	at com.intel.hibench.sparkbench.common.IOCommon$.<clinit>(IOCommon.scala)
	... 7 more
2019-03-21 22:39:27 INFO  ApplicationMaster:54 - Final app status: FAILED, exitCode: 15, (reason: User class threw exception: java.lang.ExceptionInInitializerError
	at com.intel.hibench.sparkbench.micro.ScalaTeraSort$.main(ScalaTeraSort.scala:53)
	at com.intel.hibench.sparkbench.micro.ScalaTeraSort.main(ScalaTeraSort.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$4.run(ApplicationMaster.scala:706)
Caused by: java.lang.NullPointerException
	at scala.collection.immutable.StringLike$class.split(StringLike.scala:208)
	at scala.collection.immutable.StringOps.split(StringOps.scala:29)
	at com.intel.hibench.sparkbench.common.IOCommon$.getPropertiesFromFile(IOCommon.scala:90)
	at com.intel.hibench.sparkbench.common.IOCommon$.<init>(IOCommon.scala:86)
	at com.intel.hibench.sparkbench.common.IOCommon$.<clinit>(IOCommon.scala)
	... 7 more
)
2019-03-21 22:39:27 INFO  SparkContext:54 - Invoking stop() from shutdown hook
2019-03-21 22:39:27 INFO  AbstractConnector:318 - Stopped Spark@2bac538{HTTP/1.1,[http/1.1]}{0.0.0.0:0}
```

**Comment by BalaBalaYi** [comment]
@tobegit3hub @vijayarajbala 
Same issue with @tobegit3hub. Tested on HDP 2.6.5.x (Spark 2.3) with HiBench 7.0 just now.

But i reviewed the source code in HiBench. I think the reason is that Hibench needs to deal with the log  on client side. So cluster mode can not be supported. (cluster mode support aren't mentioned in doc however, using `yarn` or `yarn-client` is the same)

**Comment by tobegit3hub** [comment]
@BalaBalaYi You're right and the HiBench client would not parse the log of `yarn-cluster` job now.

But the Spark job have been submitted. I have check the command of `spark-submit` which is reasonable and I don't think it will fail because of the log parser of HiBench. So the root cause need to be found and it is possible for HiBench to support `yarn-cluster` mode.

**Comment by BalaBalaYi** [comment]
@tobegit3hub Thx.

**Comment by hani-bassam-al-sayeh** [comment]
It worked for me when I set --deploy-mode cluster and --master yarn
