### ISSUE TITLE
metrics_reader.sh for identity workload  not working in spark streaming 

### ISSUE THREAD

**Issue by saadhsn** [intel-hadoop/HiBench#493]
When running metrics_reader.sh for identity workload, following is the error coming 
I am using spark 2.1.0 and kafka 0.8.x.x
**Starting MetricsReader for kafka topic: identity
Exception in thread "main" java.util.concurrent.ExecutionException: java.lang.NumberFormatException: For input string: "0 182.163.112.4,nbizrgdziebsaecsecujfjcqtvnp...
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at com.intel.hibench.common.streaming.metrics.KafkaCollector$$anonfun$1.apply(KafkaCollector.scala:52)
        at com.intel.hibench.common.streaming.metrics.KafkaCollector$$anonfun$1.apply(KafkaCollector.scala:52)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
        at scala.collection.AbstractTraversable.map(Traversable.scala:104)
        at com.intel.hibench.common.streaming.metrics.KafkaCollector.start(KafkaCollector.scala:52)
        at com.intel.hibench.common.streaming.metrics.MetricsReader$.delayedEndpoint$com$intel$hibench$common$streaming$metrics$MetricsReader$1(MetricsReader.scala:32)
        at com.intel.hibench.common.streaming.metrics.MetricsReader$delayedInit$body.apply(MetricsReader.scala:19)
        at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at scala.App$$anonfun$main$1.apply(App.scala:76)
        at scala.App$$anonfun$main$1.apply(App.scala:76)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
        at scala.App$class.main(App.scala:76)
        at com.intel.hibench.common.streaming.metrics.MetricsReader$.main(MetricsReader.scala:19)
        at com.intel.hibench.common.streaming.metrics.MetricsReader.main(MetricsReader.scala)
Caused by: java.lang.NumberFormatException: For input string: "0        182.163.112.4,nbizrgdziebsaecsecujfjcqtvnpcnxxwiopmddorcxnlijdizgoi,1978-10-17,0.332717,Mozi...
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Long.parseLong(Long.java:589)
        at java.lang.Long.parseLong(Long.java:631)
        at scala.collection.immutable.StringLike$class.toLong(StringLike.scala:251)
        at scala.collection.immutable.StringOps.toLong(StringOps.scala:30)
        at com.intel.hibench.common.streaming.metrics.FetchJob.call(FetchJob.scala:32)
        at com.intel.hibench.common.streaming.metrics.FetchJob.call(FetchJob.scala:24)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)**

**Comment by 2victoria** [comment]
Do you resolve it?
