### ISSUE TITLE
dfsioe/prepare fail if in background process

### ISSUE THREAD

**Issue by ZeweiChen11** [intel-hadoop/HiBench#534]
```
hdfs rm -r: /usr/lib/hadoop//bin/hadoop --config /usr/lib/hadoop//etc/hadoop fs -rm -r -skipTrash hdfs://hsw-node13:8020/HiBench/Dfsioe/Input
Deleted hdfs://hsw-node13:8020/HiBench/Dfsioe/Input
Submit MapReduce Job: /usr/lib/hadoop//bin/hadoop --config /usr/lib/hadoop//etc/hadoop jar /root/HiBench_bk/autogen/target/autogen-7.0-jar-with-dependencies.jar org.apache.hadoop.fs.dfsioe.TestDFSIOEnh -Dmapreduce.map.java.opts="-Dtest.build.data=hdfs://hsw-node13:8020/HiBench/Dfsioe/Input -Djava.net.preferIPv4Stack=true -Xmx1610612736" -Dmapreduce.reduce.java.opts="-Dtest.build.data=hdfs://hsw-node13:8020/HiBench/Dfsioe/Input -Djava.net.preferIPv4Stack=true -Xmx1610612736" -Dtest.build.data=hdfs://hsw-node13:8020/HiBench/Dfsioe/Input -write -skipAnalyze -nrFiles 16 -fileSize 1 -bufferSize 4096
TestFDSIO.0.0.4 Enhanced Version
18/01/11 04:00:59 INFO dfsioe.TestDFSIOEnh: nrFiles = 16
18/01/11 04:00:59 INFO dfsioe.TestDFSIOEnh: fileSize (MB) = 1
18/01/11 04:00:59 INFO dfsioe.TestDFSIOEnh: bufferSize = 4096
18/01/11 04:01:00 INFO client.RMProxy: Connecting to ResourceManager at hsw-node13/192.168.1.113:8032
18/01/11 04:01:01 INFO Configuration.deprecation: mapred.tasktracker.reduce.tasks.maximum is deprecated. Instead, use mapreduce.tasktracker.reduce.tasks.maximum
18/01/11 04:01:01 INFO Configuration.deprecation: mapred.tasktracker.map.tasks.maximum is deprecated. Instead, use mapreduce.tasktracker.map.tasks.maximum
18/01/11 04:01:01 INFO dfsioe.TestDFSIOEnh: maximum concurrent maps = 6
18/01/11 04:01:01 INFO dfsioe.TestDFSIOEnh: creating control file: 1 mega bytes, 16 files
java.lang.RuntimeException: Property test.build.data cannot be empty
        at org.apache.hadoop.fs.dfsioe.DfsioeConfig.safeGet(DfsioeConfig.java:137)
        at org.apache.hadoop.fs.dfsioe.DfsioeConfig.getTestRootDir(DfsioeConfig.java:45)
        at org.apache.hadoop.fs.dfsioe.DfsioeConfig.getControlDir(DfsioeConfig.java:62)
        at org.apache.hadoop.fs.dfsioe.TestDFSIOEnh.createControlFile(TestDFSIOEnh.java:640)
        at org.apache.hadoop.fs.dfsioe.TestDFSIOEnh.run(TestDFSIOEnh.java:602)
        at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
        at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:84)
        at org.apache.hadoop.fs.dfsioe.TestDFSIOEnh.main(TestDFSIOEnh.java:628)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.hadoop.util.RunJar.run(RunJar.java:221)
        at org.apache.hadoop.util.RunJar.main(RunJar.java:136)
ERROR: Hadoop job /root/HiBench_bk/autogen/target/autogen-7.0-jar-with-dependencies.jar org.apache.hadoop.fs.dfsioe.TestDFSIOEnh failed to run successfully.
Hint: You can goto /root/HiBench_bk/report/dfsioe/prepare/conf/../bench.log to check for detailed log.
Opening log tail for you:

                BAD_ID=0
                CONNECTION=0
                IO_ERROR=0
                WRONG_LENGTH=0
                WRONG_MAP=0
                WRONG_REDUCE=0
        File Input Format Counters
                Bytes Read=1798
        File Output Format Counters
                Bytes Written=90892
ERROR: micro/dfsioe prepare failed!
```

**Comment by vincent-wangzy** [comment]
Any ideas about this? I meet the same issue

**Comment by ZeweiChen11** [comment]
@vincent-wangzy Do you also meet this when let it in backgroud process?

**Comment by ZeweiChen11** [comment]
@vincent-wangzy I met this error only when running in background.

**Comment by lee212** [comment]
I encountered the same error message with small dataset configuration. I ran on the cdh docker image provided.

**Comment by handmail** [comment]
not in background process , is OK ...  -_!!

**Comment by susuleung** [comment]
"move -Dtest.build.data=${INPUT_HDFS} to the front of the OPTION variable in both run-read.sh and run-write.sh." works for me. I encounter this problem while running the benchmark in frontground.

**Comment by wenwj0** [comment]
> Try to move `-Dtest.build.data=${INPUT_HDFS}` to the front of the OPTION variable in both run-read.sh and run-write.sh. I encountered the same error message when I ran on the cdh docker image provided but this change fixes the issue wrt loading the `test.build.data` property from command line.

It works.
