### ISSUE TITLE
./datagen.sh hangs on

### ISSUE THREAD

**Issue by Aamer012** [intel-hadoop/HiBench#543]
I am working on spark streaming test using Hibench. All my tests for hadoop and spark for batch processing are going fine. But when i test for spark streaming test, ./genseedDataset.sh run sucessfully and create data in HDFS. While i run ./dataGen.sh to push the data to kafka it giving some warnings first, e.g log4j:Warn no appenders could be found for logger (org.apache.kafka.clients.producer.producerConfig)
log4j:Warn Please initialize the log4j system properly.
And than pool-1-thread-1 - starting generate data --- 
and here it hangs for long time. I  checked all the kafka settings its running fine in cluster mode, spark and hadoop also fine, configuration settings are fine. What can be the issue. How can i solve this?

Kafka version: kafka-1.0.1
spark: 2.2.0
Hadoop : 2.9.0

**Comment by Mr-San** [comment]
数据正在写入，可以通过以下命令查看Kafka中的数据量变化

ZK=rose-master-01:2181,rose-master-02:2181,rose-master-03:2181/kafka
BL=rose-master-01:9092,rose-master-02:9092,rose-master-03:9092
T=identity
kafka-run-class kafka.tools.GetOffsetShell --broker-list $BL  -time -1 --topic $T
kafka-run-class kafka.tools.GetOffsetShell --broker-list $BL  -time -2 --topic $T

**Comment by 2victoria** [comment]
I meet the problems.
kafka_2.11-0.10.2.1 ,when run ./dataGen.sh,appear the problem:
SLF4J: Failed toString() invocation on an object of type [org.apache.kafka.common.Cluster]
java.lang.NullPointerException
at org.apache.kafka.common.PartitionInfo.toString(PartitionInfo.java:72)
at java.lang.String.valueOf(String.java:2994)
at java.lang.StringBuilder.append(StringBuilder.java:131)
at java.util.AbstractCollection.toString(AbstractCollection.java:462)
at java.lang.String.valueOf(String.java:2994)
at java.lang.StringBuilder.append(StringBuilder.java:131)
at org.apache.kafka.common.Cluster.toString(Cluster.java:171)
at org.slf4j.helpers.MessageFormatter.safeObjectAppend(MessageFormatter.java:304)
at org.slf4j.helpers.MessageFormatter.deeplyAppendParameter(MessageFormatter.java:276)
at org.slf4j.helpers.MessageFormatter.arrayFormat(MessageFormatter.java:230)
at org.slf4j.helpers.MessageFormatter.format(MessageFormatter.java:152)
at org.slf4j.impl.Log4jLoggerAdapter.debug(Log4jLoggerAdapter.java:251)
at org.apache.kafka.clients.producer.internals.Metadata.update(Metadata.java:141)
at org.apache.kafka.clients.NetworkClient.handleMetadataResponse(NetworkClient.java:...
at org.apache.kafka.clients.NetworkClient.handleCompletedReceives(NetworkClient.java...
at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:199)
at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:191)
at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:122)
at java.lang.Thread.run(Thread.java:748)
How to solve it?

**Comment by MaginaLX** [comment]
I met the same problem before.

My solution was to change the version of Kafka from 2.1.0(Scala 2.11) to 0.8.2.2(Scala 2.10) as Hibench/docs/run-streamingbench.md suggests, then run genSeedDataset.sh again. 

And the problem was solved.
