### ISSUE TITLE
SLF4J: Failed toString() invocation on an object of type [org.apache.kafka.common.Cluster]

### ISSUE THREAD

**Issue by 2victoria** [intel-hadoop/HiBench#548]
kafka_2.11-0.10.2.1 ,when run ./dataGen.sh,appear the problem:
SLF4J: Failed toString() invocation on an object of type [org.apache.kafka.common.Cluster]
java.lang.NullPointerException
        at org.apache.kafka.common.PartitionInfo.toString(PartitionInfo.java:72)
        at java.lang.String.valueOf(String.java:2994)
        at java.lang.StringBuilder.append(StringBuilder.java:131)
        at java.util.AbstractCollection.toString(AbstractCollection.java:462)
        at java.lang.String.valueOf(String.java:2994)
        at java.lang.StringBuilder.append(StringBuilder.java:131)
        at org.apache.kafka.common.Cluster.toString(Cluster.java:171)
        at org.slf4j.helpers.MessageFormatter.safeObjectAppend(MessageFormatter.java:304)
        at org.slf4j.helpers.MessageFormatter.deeplyAppendParameter(MessageFormatter.java:276)
        at org.slf4j.helpers.MessageFormatter.arrayFormat(MessageFormatter.java:230)
        at org.slf4j.helpers.MessageFormatter.format(MessageFormatter.java:152)
        at org.slf4j.impl.Log4jLoggerAdapter.debug(Log4jLoggerAdapter.java:251)
        at org.apache.kafka.clients.producer.internals.Metadata.update(Metadata.java:141)
        at org.apache.kafka.clients.NetworkClient.handleMetadataResponse(NetworkClient.java:...
        at org.apache.kafka.clients.NetworkClient.handleCompletedReceives(NetworkClient.java...
        at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:199)
        at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:191)
        at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:122)
        at java.lang.Thread.run(Thread.java:748)
How to solve it?

**Comment by cptekam** [comment]
I am also facing the same issue
