### ISSUE TITLE
sparkbench failing with ExceptionInInitializerError

### ISSUE THREAD

**Issue by vijayarajbala** [intel-hadoop/HiBench#550]
Anyone, getting this issue. 

18/06/10 11:34:03 INFO cluster.YarnClientSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.8
Exception in thread "main" java.lang.ExceptionInInitializerError
        at com.intel.hibench.sparkbench.micro.ScalaSort$.main(ScalaSort.scala:43)
        at com.intel.hibench.sparkbench.micro.ScalaSort.main(ScalaSort.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:730)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.NullPointerException
        at scala.collection.immutable.StringLike$class.split(StringLike.scala:201)
        at scala.collection.immutable.StringOps.split(StringOps.scala:31)
        at com.intel.hibench.sparkbench.common.IOCommon$.getPropertiesFromFile(IOCommon.scala:90)
        at com.intel.hibench.sparkbench.common.IOCommon$.<init>(IOCommon.scala:86)
        at com.intel.hibench.sparkbench.common.IOCommon$.<clinit>(IOCommon.scala)
        ... 11 more
18/06/10 11:34:03 INFO spark.SparkContext: Invoking stop() from shutdown hook
18/06/10 11:34:03 INFO ui.SparkUI: Stopped Spark web UI at http://10.195.115.39:4040

**Comment by vijayarajbala** [comment]
It worked with this.

 mvn -Psparkbench -Dspark=1.6 -Dscala=2.10 clean package

**Comment by hani-bassam-al-sayeh** [comment]
It worked for me when I set '--deploy-mode client' and '--master yarn'
