### ISSUE TITLE
Issue running spark terrrasort

### ISSUE THREAD

**Issue by gilbertc777** [intel-hadoop/HiBench#571]
All: 
I am running into some issues on running spark terrasort for Hibench.

Please see the following errors:

Exception in thread "main" java.io.EOFException: End of File Exception between local host is: "hpc-cluster-cn1-rdma.local.rdma/192.18.18.1"; destination host is: "hpc-cluster-cn1-rdma":9000;  : java.io.EOFException; For more details see:  http://wiki.apache.org/hadoop/EOFException                                                                                                             at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)                                                                                                                       at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)                                                                                                at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)                                                                                        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)                                                                                                                             at org.apache.hadoop.net.NetUtils.wrapWithMessage(NetUtils.java:792)                                                                                                                           at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:765)                                                                                                                             at org.apache.hadoop.ipc.Client.call(Client.java:1479)                                                                                                                                         at org.apache.hadoop.ipc.Client.call(Client.java:1412)                                                                                                                                         at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:229)                                                                                                          at com.sun.proxy.$Proxy20.getFileInfo(Unknown Source)                                                                                                                                          at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getFileInfo(ClientNamenodeProtocolTranslatorPB.java:771)                                                               at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                                                                                                                                 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)                                                                                                               at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)                                                                                                       at java.lang.reflect.Method.invoke(Method.java:498)                                                                                                                                            at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:191)                                                                                             at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:102)                                                                                                   at com.sun.proxy.$Proxy21.getFileInfo(Unknown Source)                                                                                                                                          at org.apache.hadoop.hdfs.DFSClient.getFileInfo(DFSClient.java:2108)                                                                                                                           at org.apache.hadoop.hdfs.DistributedFileSystem$22.doCall(DistributedFileSystem.java:1305)                                                                                                     at org.apache.hadoop.hdfs.DistributedFileSystem$22.doCall(DistributedFileSystem.java:1301)                                                                                                     at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)                                                                                                         at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:1317)                                                                                                 at org.apache.hadoop.fs.Globber.getFileStatus(Globber.java:57)                                                                                                                                 at org.apache.hadoop.fs.Globber.glob(Globber.java:252)                                                                                                                                         at org.apache.hadoop.fs.FileSystem.globStatus(FileSystem.java:1676)                                                                                                                            at org.apache.hadoop.mapreduce.lib.input.FileInputFormat.singleThreadedListStatus(FileInputFormat.java:294)                                                                                    at org.apache.hadoop.mapreduce.lib.input.FileInputFormat.listStatus(FileInputFormat.java:265)                                                                                                  at org.apache.hadoop.mapreduce.lib.input.FileInputFormat.getSplits(FileInputFormat.java:387)                                                                                                   at org.apache.hadoop.examples.terasort.TeraInputFormat.getSplits(TeraInputFormat.java:294)                                                                                                     at org.apache.spark.rdd.NewHadoopRDD.getPartitions(NewHadoopRDD.scala:130)                                                                                                                     at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:253)                                                                                                                         at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:251)                                                                                                                         at scala.Option.getOrElse(Option.scala:121)                                                                                                                                                    at org.apache.spark.rdd.RDD.partitions(RDD.scala:251)                                                                                                                                          at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:49)                                                                                                              at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:253)                                                                                                                         at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:251)                                                                                                                         at scala.Option.getOrElse(Option.scala:121)                                                                                                                                                    at org.apache.spark.rdd.RDD.partitions(RDD.scala:251)                                                                                                                                          at org.apache.spark.BaseRangePartitioner.(BaseRangePartitioner.scala:52)                                                                                                                 at com.intel.hibench.sparkbench.micro.ScalaTeraSort$.main(ScalaTeraSort.scala:56)                                                                                                              at com.intel.hibench.sparkbench.micro.ScalaTeraSort.main(ScalaTeraSort.scala)                                                                                                                  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                                                                                                                                 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)                                                                                                               at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)                                                                                                       at java.lang.reflect.Method.invoke(Method.java:498)                                                                                                                                            at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)                                                                                                                at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:849)                                                                                     at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:167)                                                                                                                      at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:195)                                                                                                                           at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)                                                                                                                          at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:924)                                                                                                                 at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:933)                                                                                                                            at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)                                                                                                                         Caused by: java.io.EOFException                                                                                                                                                                        at java.io.DataInputStream.readInt(DataInputStream.java:392)                                                                                                                                   at org.apache.hadoop.ipc.Client$Connection.receiveRpcResponse(Client.java:1084)                                                                                                                at org.apache.hadoop.ipc.Client$Connection.run(Client.java:979)                                                                                                                        2019-02-07 19:04:32 INFO  SparkContext:54 - Invoking stop() from shutdown hook                                                                                                                 2019-02-07 19:04:32 INFO  AbstractConnector:318 - Stopped Spark@4d4d48a6{HTTP/1.1,[http/1.1]}{0.0.0.0:4040}                                                                                    2019-02-07 19:04:32 INFO  SparkUI:54 - Stopped Spark web UI at http://hpc-cluster-cn1-rdma.local.rdma:4040                                                                                     2019-02-07 19:04:32 INFO  StandaloneSchedulerBackend:54 - Shutting down all executors                                                                                                          2019-02-07 19:04:32 INFO  CoarseGrainedSchedulerBackend$DriverEndpoint:54 - Asking each executor to shut down                                                                                  2019-02-07 19:04:32 INFO  MapOutputTrackerMasterEndpoint:54 - MapOutputTrackerMasterEndpoint stopped!                                                                                          2019-02-07 19:04:32 WARN  TransportChannelHandler:78 - Exception in connection from /192.18.18.5:45646                                                                                         java.io.IOException: Connection reset by peer                                                                                                                                                          at sun.nio.ch.FileDispatcherImpl.read0(Native Method)                                                                                                                                          at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)                                                                                                                                  at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)                                                                                                                                     at sun.nio.ch.IOUtil.read(IOUtil.java:192)                                                                                                                                                     at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)                                                                                                                               at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)                                                                                                      at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1106)                                                                                                                       at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:343)                                                                                                         at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)                                                                                             at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)                                                                                                                 at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)                                                                                                       at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)                                                                                                                at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)                                                                                                                                at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)                                                                                                at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)                                                                                   at java.lang.Thread.run(Thread.java:748)                                                                                                                                               2019-02-07 19:04:32 WARN  TransportChannelHandler:78 - Exception in connection from /192.18.18.9:44775                                                                                         java.io.IOException: Connection reset by peer                                                                                                                                                          at sun.nio.ch.FileDispatcherImpl.read0(Native Method)                                                                                                                                          at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)                                                                                                                                  at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)                                                                                                                                     at sun.nio.ch.IOUtil.read(IOUtil.java:192)                                                                                                                                                     at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)                                                                                                                               at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)                                                                                                      at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1106)                                                                                                                       at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:343)                                                                                                         at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)                                                                                             at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)                                                                                                                 at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)                                                                                                       at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)                                                                                                                at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)                                                                                                                                at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)                                                                                                at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)                                                                                   at java.lang.Thread.run(Thread.java:748)                                                                                                                                               2019-02-07 19:04:32 WARN  TransportChannelHandler:78 - Exception in connection from /192.18.18.3:35271                                                                                         java.io.IOException: Connection reset by peer                                                                                                                                                          at sun.nio.ch.FileDispatcherImpl.read0(Native Method)                                                                                                                                          at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)                                                                                                                                  at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)                                                                                                                                     at sun.nio.ch.IOUtil.read(IOUtil.java:192)                                                                                                                                                     at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)                                                                                                                               at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)                                                                                                      at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1106)                                                                                                                       at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:343)                                                                                                         at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)                                                                                             at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)                                                                                                                 at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)                                                                                                       at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)                                                                                                                at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)                                                                                                                                at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)                                                                                                at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)                                                                                   at java.lang.Thread.run(Thread.java:748)                                                                                                                                               2019-02-07 19:04:32 WARN  TransportChannelHandler:78 - Exception in connection from /192.18.18.6:34183                                                                                         java.io.IOException: Connection reset by peer                                                                                                                                                          at sun.nio.ch.FileDispatcherImpl.read0(Native Method)                                                                                                                                          at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)                                                                                                                                  at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)                                                                                                                                     at sun.nio.ch.IOUtil.read(IOUtil.java:192)                                                                                                                                                     at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)                                                                                                                               at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)                                                                                                      at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1106)                                                                                                                       at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:343)                                                                                                         at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)                                                                                             at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)                                                                                                                 at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)                                                                                                       at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)                                                                                                                at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)                                                                                                                                at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)                                                                                                at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)                                                                                   at java.lang.Thread.run(Thread.java:748)                                                                                                                                               2019-02-07 19:04:32 WARN  TransportChannelHandler:78 - Exception in connection from /192.18.18.8:36367                                                                                         java.io.IOException: Connection reset by peer                                                                                                                                                          at sun.nio.ch.FileDispatcherImpl.read0(Native Method)                                                                                                                                          at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)                                                                                                                                  at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)                                                                                                                                     at sun.nio.ch.IOUtil.read(IOUtil.java:192)                                                                                                                                                     at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)                                                                                                                               at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)                                                                                                      at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1106)                                                                                                                       at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:343)                                                                                                         at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)                                                                                             at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)                                                                                                                 at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)                                                                                                       at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)                                                                                                                at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)                                                                                                                                at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)                                                                                                at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)                                                                                   at java.lang.Thread.run(Thread.java:748)                                                                                                                                               2019-02-07 19:04:32 INFO  RdmaNode:213 - Exiting RdmaNode Listening Server                                                                                                                     2019-02-07 19:04:32 INFO  RdmaBufferManager:218 - Rdma buffers allocation statistics:
--

**Comment by petro-rudenko** [comment]
Could be that teragen didn't finish successfully. Make sure your hdfs is running, and teragen script finished successfully and all data is on hdfs.
