### ISSUE TITLE
HiBench on Amazon EMR and S3

### ISSUE THREAD

**Issue by honto-ming** [intel-hadoop/HiBench#81]
Hi there,

I am hoping to use HiBench for a school project to test the IO throughput of using Amazon S3 as the datasource for Amazon EMR, vs. using HDFS on the EMR instances as the datasource (it is for a school project). However, I am running into trouble pointing DFSIO Enhanced to read and write from and to S3. 

Here is what I've done:

on `Hibench/bin/hibench-config.sh`, 
`export DATA_HDFS=s3://<mybucket>`

However, when I try running `bash run-write.sh` under the `dfsio/bin` directory to start the DFSIO-e write test (I did not run prepare.sh beforehand because to my understanding you do not need to run it prior to the write test), I get the following error:

`15/04/02 05:59:37 INFO dfsioe.TestDFSIOEnh: creating control file: 100 mega bytes, 20 files
java.lang.IllegalArgumentException: Wrong FS: s3://cmpt886-testbucket/benchmarks/TestDFSIO-Enh/io_control, expected: hdfs://172.31.41.39:9000
	at org.apache.hadoop.fs.FileSystem.checkPath(FileSystem.java:647)
	at org.apache.hadoop.hdfs.DistributedFileSystem.getPathName(DistributedFileSystem.java:191)
	at org.apache.hadoop.hdfs.DistributedFileSystem.access$000(DistributedFileSystem.java:102)
	at org.apache.hadoop.hdfs.DistributedFileSystem$11.doCall(DistributedFileSystem.java:595)
	at org.apache.hadoop.hdfs.DistributedFileSystem$11.doCall(DistributedFileSystem.java:591)
	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
	at org.apache.hadoop.hdfs.DistributedFileSystem.delete(DistributedFileSystem.java:591)
	at org.apache.hadoop.fs.dfsioe.TestDFSIOEnh.createControlFile(TestDFSIOEnh.java:636)
	at org.apache.hadoop.fs.dfsioe.TestDFSIOEnh.run(TestDFSIOEnh.java:598)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:84)
	at org.apache.hadoop.fs.dfsioe.TestDFSIOEnh.main(TestDFSIOEnh.java:624)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:212)
15/04/02 05:59:43 INFO fs.EmrFileSystem: Consistency enabled, using com.amazon.ws.emr.hadoop.fs.s3n2.S3NativeFileSystem2 as filesystem implementation
`

I also tried setting the value in `<property><name>fs.default.name</name><value>hdfs://172.31.41.39:9000</value></property>` from `hdfs://..` to `s3://<bucketname>` but then I get the following error:

`15/04/02 05:55:48 INFO mapreduce.Cluster: Failed to use org.apache.hadoop.mapred.YarnClientProtocolProvider due to error: Error in instantiating YarnClient
java.io.IOException: Cannot initialize Cluster. Please check your configuration for mapreduce.framework.name and the correspond server addresses.
	at org.apache.hadoop.mapreduce.Cluster.initialize(Cluster.java:120)
	at org.apache.hadoop.mapreduce.Cluster.<init>(Cluster.java:82)
	at org.apache.hadoop.mapreduce.Cluster.<init>(Cluster.java:75)
	at org.apache.hadoop.mapred.JobClient.init(JobClient.java:470)
	at org.apache.hadoop.mapred.JobClient.<init>(JobClient.java:449)
	at org.apache.hadoop.fs.dfsioe.TestDFSIOEnh.run(TestDFSIOEnh.java:578)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:84)
	at org.apache.hadoop.fs.dfsioe.TestDFSIOEnh.main(TestDFSIOEnh.java:624)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:212)
`

Is it possible to point DFSIOe to S3? And if so, can you tell me what configuration settings to change?

Honto

**Comment by adrian-wang** [comment]
We didn't test HiBench on S3 before, but I think it should work.
From the log you provided, it seems your hadoop is not configured well for S3. Maybe you should refer to documentation of S3 about how to use S3 with Hadoop for help.

**Comment by ZuluPro** [comment]
Hello @adrian-wang 

By configuring `fs.default.name` with `s3a://`, I have the same kind of error: `org.apache.hadoop.mapred.YarnClientProtocolProvider due to error: Error in instantiating YarnClient `

Do you think Hi-bench could officialy support S3 benchmarks ?

**Comment by adrian-wang** [comment]
HiBench only runs some big data workloads on cluster, I think you should verify your S3 settings with yarn settings. Make sure your settings work before you begin your benchmark.

**Comment by bgaborg** [comment]
>export DATA_HDFS=s3://<mybucket>

you should use **s3a**://<mybucket>

**Comment by weinick** [comment]
@bgaborg : I'm using s3a://, but met a similar error. Did you run successfully before? Can you share your configuration if it works? Thanks.

19/06/12 20:02:25 INFO dfsioe.DfsioeConfig: Setting testRootDir to 's3a://hibenchd
ata/HiBench/Dfsioe/Input'
java.lang.IllegalArgumentException: Wrong FS: s3a://hibenchdata/HiBench/Dfsioe/Inp
ut/io_control, expected: hdfs://hacluster
at org.apache.hadoop.fs.FileSystem.checkPath(FileSystem.java:665)
at org.apache.hadoop.hdfs.DistributedFileSystem.getPathName(DistributedFil
eSystem.java:218)
at org.apache.hadoop.hdfs.DistributedFileSystem$17.doCall(DistributedFileS
ystem.java:839)

**Comment by adrian-wang** [comment]
@weinick I think you should config your `fs.defaultFs` in core-site.xml to `s3a://...`.

**Comment by weinick** [comment]
@adrian-wang Hi Adrian, thanks for your reply. As you said, I tried to update fs.defaultFs on my YARN core-site.xml, it still didn't work but the error message changed. I have added S3 AK/SK into this file also and  I can run S3 based wordcount job. I'm pretty sure that the bucket name is correct and the credential is correct. Do you have any other idea?

19/06/12 22:04:48 INFO mapreduce.Job:  map 0% reduce 0%
19/06/12 22:04:48 INFO mapreduce.Job: Job job_1560180791815_0030 failed with state FAIL
e FAILED due to: Application application_1560180791815_0030 failed 2 times due tontaine
 AM Container for appattempt_1560180791815_0030_000002 exited with  exitCode: -10
00
Failing this attempt.Diagnostics: doesBucketExist on hibenchdata: com.amazonaws.Amode :
mazonClientException: No AWS Credentials provided by BasicAWSCredentialsProvider 
EnvironmentVariableCredentialsProvider SharedInstanceProfileCredentialsProvider :mode :
 com.amazonaws.AmazonClientException: The requested metadata is not found at http
://169.254.169.254/latest/meta-data/iam/security-credentials/: No AWS Credentials
 provided by BasicAWSCredentialsProvider EnvironmentVariableCredentialsProvider Se FAIL
haredInstanceProfileCredentialsProvider : com.amazonaws.AmazonClientException: Thntaine
e requested metadata is not found at http://169.254.169.254/latest/meta-data/iam/
security-credentials/mazonC
org.apache.hadoop.fs.s3a.AWSClientIOException: doesBucketExist on hibenchdata: conmentV
m.amazonaws.AmazonClientException: No AWS Credentials provided by BasicAWSCredentws.Ama
ialsProvider EnvironmentVariableCredentialsProvider SharedInstanceProfileCredenti/lates
alsProvider : com.amazonaws.AmazonClientException: The requested metadata is not dentia
found at http://169.254.169.254/latest/meta-data/iam/security-credentials/: No AWsProvi
S Credentials provided by BasicAWSCredentialsProvider EnvironmentVariableCredenti http:
alsProvider SharedInstanceProfileCredentialsProvider : com.amazonaws.AmazonClient
Exception: The requested metadata is not found at http://169.254.169.254/latest/mm.amaz
eta-data/iam/security-credentials/

**Comment by adrian-wang** [comment]
@weinick Can you use the same configuration to do a `hadoop fs -ls /`? Your log appears there's something wrong with credential settings.
